package technology.co.beyondimagination.beyondbabynames;

import android.app.Activity;
import android.app.AlertDialog;
import android.content.SharedPreferences;
import android.content.Context;
import android.content.ClipData;
import android.content.ClipboardManager;
import android.graphics.*;
import android.os.Bundle;
import android.security.keystore.KeyGenParameterSpec;
import android.security.keystore.KeyProperties;
import android.text.InputType;
import android.view.MotionEvent;
import android.view.View;
import android.widget.EditText;
import android.widget.Toast;
import java.io.*;
import java.net.HttpURLConnection;
import java.net.URL;
import java.nio.charset.StandardCharsets;
import java.security.*;
import javax.crypto.*;
import org.json.*;
import java.util.*;

/** Private, offline discovery and swipe v1 based on the shared iOS name library. */
public final class MainActivity extends Activity {
    @Override public void onCreate(Bundle state) { super.onCreate(state); setContentView(new NamesView()); }
    private final class NamesView extends View {
        final Paint p=new Paint(Paint.ANTI_ALIAS_FLAG); final SharedPreferences prefs=getSharedPreferences("names",MODE_PRIVATE);
        final String[][] names={{"Aaliyah","Arabic","Exalted and noble","Graceful · Modern"},{"Amara","Igbo","Grace","Global · Gentle"},{"Ari","Hebrew","Lion","Short · Bold"},{"Aurora","Latin","Dawn","Celestial · Romantic"},{"Ezra","Hebrew","Helper","Biblical · Gentle"},{"Imani","Swahili","Faith","Spiritual · Global"},{"Isla","Scottish","Island","Nature · Soft"},{"Kai","Hawaiian","Sea","Nature · Short"},{"Luca","Italian","Bringer of light","Bright · Modern"},{"Luna","Latin","Moon","Celestial · Dreamy"},{"Maeve","Irish","She who intoxicates","Mythic · Strong"},{"Noah","Hebrew","Rest and comfort","Biblical · Peaceful"},{"Nova","Latin","New","Celestial · Bold"},{"Sage","Latin","Wise","Nature · Calm"},{"Zuri","Swahili","Beautiful","Bright · Global"}};
        int tab=0,index=0; String familyName,coupleCode,coupleId,syncStatus="Create or join a private space."; final Set<String> favorites=new HashSet<>(),matches=new HashSet<>();
        NamesView(){super(MainActivity.this); Collections.addAll(favorites,prefs.getString("favorites","").split(",")); favorites.remove(""); familyName=prefs.getString("familyName","");coupleCode=prefs.getString("coupleCode","");coupleId=prefs.getString("coupleId",""); if(memberToken()!=null) { syncStatus="Private space connected."; refreshCoupleState(); }}
        void text(Canvas c,String s,float x,float y,float size,int color,boolean b){p.setColor(color);p.setTextSize(size);p.setTypeface(Typeface.create("sans",b?1:0));p.setStyle(Paint.Style.FILL);c.drawText(s,x,y,p);}
        void box(Canvas c,float l,float t,float r,float b,float rad,int color){p.setColor(color);p.setStyle(Paint.Style.FILL);c.drawRoundRect(new RectF(l,t,r,b),rad,rad,p);}
        @Override protected void onDraw(Canvas c){float w=getWidth(),h=getHeight();c.drawColor(Color.rgb(18,10,36));text(c,"BEYOND BABY",22,42,22,Color.WHITE,true);text(c,"Find the one",22,66,13,Color.rgb(206,194,226),false);if(tab==0)discover(c,w);else if(tab==1)swipe(c,w);else if(tab==2)favs(c,w);else together(c,w);nav(c,w,h);}
        void discover(Canvas c,float w){String[] n=names[(index+9)%names.length];box(c,18,92,w-18,256,28,Color.rgb(108,45,220));text(c,"YOUR DAILY DISCOVERY",40,126,12,Color.rgb(255,211,246),true);text(c,n[0],40,184,43,Color.WHITE,true);text(c,n[2],40,215,17,Color.WHITE,false);text(c,"A thoughtful name, surfaced just for you.",40,240,13,Color.rgb(240,225,255),false);text(c,"EXPLORE NAMES",22,302,12,Color.rgb(255,78,200),true);int y=326;for(int i=0;i<4;i++){String[] item=names[(index+i)%names.length];box(c,18,y,w-18,y+76,18,Color.rgb(35,25,60));text(c,item[0],38,y+31,20,Color.WHITE,true);text(c,item[1]+" · "+item[2],38,y+55,13,Color.rgb(202,193,220),false);text(c,favorites.contains(item[0])?"♥":"♡",w-56,y+45,25,Color.rgb(255,61,197),true);y+=88;}}
        void swipe(Canvas c,float w){String[] n=names[index];text(c,"SWIPE TO DECIDE",22,108,12,Color.rgb(255,78,200),true);box(c,28,138,w-28,442,34,Color.rgb(47,27,78));text(c,n[0],w/2-60,240,42,Color.WHITE,true);text(c,n[1],w/2-40,273,16,Color.rgb(230,215,250),false);text(c,n[2],w/2-92,309,18,Color.WHITE,false);text(c,n[3],w/2-95,341,14,Color.rgb(224,194,250),false);box(c,30,474,126,534,30,Color.rgb(70,62,92));box(c,w/2-48,474,w/2+48,534,30,Color.rgb(108,45,220));box(c,w-126,474,w-30,534,30,Color.rgb(255,61,197));text(c,"PASS",48,511,13,Color.WHITE,true);text(c,"MAYBE",w/2-27,511,13,Color.WHITE,true);text(c,"LOVE",w-102,511,13,Color.WHITE,true);text(c,"Your loves stay privately on this device.",22,578,14,Color.rgb(203,196,221),false);}
        String fullName(String first){return familyName.trim().isEmpty()?first:first+" "+familyName.trim();}
        String initials(String first){StringBuilder value=new StringBuilder();for(String part:fullName(first).split("\\s+"))if(!part.isEmpty())value.append(Character.toUpperCase(part.charAt(0)));return value.toString();}
        String flow(String first){String family=familyName.replaceAll("[^\\p{L}]","");if(family.isEmpty())return "Add a family name to hear the complete rhythm";int delta=Math.abs(first.length()-family.length());return delta<=2?"Balanced, even rhythm":first.length()<family.length()?"Crisp first name, flowing finish":"Expressive first name, concise finish";}
        void favs(Canvas c,float w){text(c,"YOUR SHORTLIST",22,108,12,Color.rgb(255,78,200),true);box(c,18,128,w-18,268,22,Color.rgb(47,27,78));text(c,"FAMILY NAME PREVIEW",38,160,11,Color.rgb(255,78,200),true);text(c,"Hear the whole name",38,193,23,Color.WHITE,true);text(c,familyName.isEmpty()?"Tap to add a family name":familyName,38,225,16,Color.rgb(225,211,242),false);text(c,"Private on this device · tap to edit",38,249,12,Color.rgb(174,160,194),false);text(c,favorites.size()+" names loved",22,310,26,Color.WHITE,true);int y=332;for(String[] n:names)if(favorites.contains(n[0])){box(c,18,y,w-18,y+78,18,Color.rgb(35,25,60));box(c,32,y+14,80,y+62,14,Color.rgb(108,45,220));text(c,initials(n[0]),44,y+45,15,Color.WHITE,true);text(c,fullName(n[0]),94,y+31,19,Color.WHITE,true);text(c,flow(n[0]),94,y+56,12,Color.rgb(202,193,220),false);y+=90;}if(favorites.isEmpty())text(c,"Love names in Swipe to build your list.",22,354,15,Color.rgb(202,193,220),false);}
        void together(Canvas c,float w){text(c,"COUPLE MODE",22,108,12,Color.rgb(255,78,200),true);box(c,18,138,w-18,355,24,Color.rgb(35,25,60));text(c,"Discover together",38,180,25,Color.WHITE,true);text(c,"Private picks. Only shared loves become matches.",38,210,14,Color.rgb(202,193,220),false);if(memberToken()==null){box(c,38,236,w-38,286,16,Color.rgb(255,61,197));text(c,"CREATE PRIVATE SPACE",54,267,14,Color.WHITE,true);box(c,38,296,w-38,346,16,Color.rgb(108,45,220));text(c,"JOIN WITH INVITE CODE",54,327,14,Color.WHITE,true);}else{box(c,38,236,w-38,286,16,Color.rgb(108,45,220));text(c,coupleCode.isEmpty()?"CONNECTED":coupleCode,54,267,14,Color.WHITE,true);text(c,"Tap code to copy · tap below to refresh",38,304,12,Color.rgb(174,160,194),false);box(c,38,314,w-38,354,16,Color.rgb(70,62,92));text(c,"REFRESH SHARED MATCHES ("+matches.size()+")",54,340,12,Color.WHITE,true);}text(c,syncStatus,22,390,14,Color.rgb(202,193,220),false);}
        void nav(Canvas c,float w,float h){String[] labels={"Discover","Swipe","Favorites","Together"};for(int i=0;i<4;i++){float x=w*(i+.5f)/4;int col=i==tab?Color.rgb(255,61,197):Color.rgb(173,163,192);text(c,i==0?"✦":i==1?"↔":i==2?"♥":"♧",x-8,h-49,20,col,true);text(c,labels[i],x-28,h-25,11,col,i==tab);}}
        void persist(){prefs.edit().putString("favorites",String.join(",",favorites)).apply();}
        String memberToken(){return SecretVault.read(MainActivity.this,"coupleMemberToken");}
        void createCouple(){syncStatus="Creating private space…";invalidate();new Thread(()->{try{JSONObject response=callApi(new JSONObject().put("action","create").put("displayName","Me"),null);String token=response.getString("memberToken");SecretVault.save(MainActivity.this,"coupleMemberToken",token);coupleCode=response.getString("inviteCode");coupleId=response.getString("coupleId");prefs.edit().putString("coupleCode",coupleCode).putString("coupleId",coupleId).apply();syncStatus="Share your invite code with your partner.";}catch(Exception error){syncStatus="Could not create space: "+error.getMessage();}post(()->invalidate());}).start();}
        void promptJoin(){final EditText input=new EditText(MainActivity.this);input.setSingleLine(true);input.setHint("BBN-XXXX-XXXX-XXXX-XXXX");input.setInputType(InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_FLAG_CAP_CHARACTERS);new AlertDialog.Builder(MainActivity.this).setTitle("Join private space").setMessage("Enter the invitation code from your partner.").setView(input).setNegativeButton("Cancel",null).setPositiveButton("Join",(dialog,which)->joinCouple(input.getText().toString().trim())).show();}
        void joinCouple(String invite){syncStatus="Joining private space…";invalidate();new Thread(()->{try{JSONObject response=callApi(new JSONObject().put("action","join").put("inviteCode",invite).put("displayName","Me"),null);SecretVault.save(MainActivity.this,"coupleMemberToken",response.getString("memberToken"));coupleCode=invite.toUpperCase(Locale.US);coupleId=response.getString("coupleId");prefs.edit().putString("coupleCode",coupleCode).putString("coupleId",coupleId).apply();syncStatus="Connected. Syncing private picks.";refreshCoupleState();}catch(Exception error){syncStatus="Could not join: "+error.getMessage();post(()->invalidate());}}).start();}
        void saveCouplePick(String name,String decision){String token=memberToken();if(token==null)return;new Thread(()->{try{callApi(new JSONObject().put("action","savePick").put("name",name).put("decision",decision),token);refreshCoupleState();}catch(Exception ignored){}}).start();}
        void refreshCoupleState(){String token=memberToken();if(token==null)return;new Thread(()->{try{JSONObject state=callApi(new JSONObject().put("action","state"),token);matches.clear();JSONArray list=state.optJSONArray("matches");if(list!=null)for(int i=0;i<list.length();i++)matches.add(list.getString(i));syncStatus=state.optInt("memberCount",0)==2?"Connected — shared loves are ready.":"Waiting for your partner to join.";}catch(Exception error){syncStatus="Sync unavailable: "+error.getMessage();}post(()->invalidate());}).start();}
        JSONObject callApi(JSONObject body,String token)throws Exception{HttpURLConnection connection=(HttpURLConnection)new URL("https://beyondimagination.co.technology/beyond-baby-names/api/couples.php").openConnection();connection.setRequestMethod("POST");connection.setConnectTimeout(12000);connection.setReadTimeout(12000);connection.setDoOutput(true);connection.setRequestProperty("Content-Type","application/json");if(token!=null)connection.setRequestProperty("Authorization","Bearer "+token);try(OutputStream output=connection.getOutputStream()){output.write(body.toString().getBytes(StandardCharsets.UTF_8));}InputStream stream=connection.getResponseCode()>=400?connection.getErrorStream():connection.getInputStream();StringBuilder result=new StringBuilder();try(BufferedReader reader=new BufferedReader(new InputStreamReader(stream,StandardCharsets.UTF_8))){String line;while((line=reader.readLine())!=null)result.append(line);}JSONObject response=new JSONObject(result.toString());if(connection.getResponseCode()<200||connection.getResponseCode()>299)throw new IOException(response.optString("error","server error"));return response;}
        void editFamilyName(){final EditText input=new EditText(MainActivity.this);input.setSingleLine(true);input.setHint("Family name");input.setInputType(InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_FLAG_CAP_WORDS);input.setText(familyName);input.setSelection(input.length());new AlertDialog.Builder(MainActivity.this).setTitle("Hear the whole name").setMessage("Try a surname to preview rhythm and initials. It stays private on this device.").setView(input).setNegativeButton("Cancel",null).setNeutralButton("Clear",(dialog,which)->{familyName="";prefs.edit().remove("familyName").apply();invalidate();}).setPositiveButton("Save",(dialog,which)->{familyName=input.getText().toString().trim();prefs.edit().putString("familyName",familyName).apply();invalidate();}).show();}
        @Override public boolean onTouchEvent(MotionEvent e){if(e.getAction()!=MotionEvent.ACTION_UP)return true;float x=e.getX(),y=e.getY(),w=getWidth(),h=getHeight();if(y>h-85){tab=Math.min(3,(int)(x/(w/4)));invalidate();return true;}if(tab==0&&y>326&&y<680){int row=(int)((y-326)/88);if(row<4){String name=names[(index+row)%names.length][0];if(!favorites.add(name))favorites.remove(name);persist();}}else if(tab==1&&y>474&&y<550){String decision=x>w*.66f?"love":x<w*.33f?"pass":"maybe";if("love".equals(decision)){favorites.add(names[index][0]);persist();}saveCouplePick(names[index][0],decision);index=(index+1)%names.length;}else if(tab==2&&y>128&&y<268){editFamilyName();}else if(tab==3){if(memberToken()==null&&y>236&&y<286)createCouple();else if(memberToken()==null&&y>296&&y<346)promptJoin();else if(memberToken()!=null&&y>236&&y<286){ClipboardManager clipboard=(ClipboardManager)getSystemService(CLIPBOARD_SERVICE);clipboard.setPrimaryClip(ClipData.newPlainText("Beyond Baby Names invite",coupleCode));Toast.makeText(MainActivity.this,"Invite code copied",Toast.LENGTH_SHORT).show();}else if(memberToken()!=null&&y>314&&y<354)refreshCoupleState();}invalidate();return true;}
    }
    private static final class SecretVault {
        private static final String KEY="BeyondBabyNamesCoupleKey", PREF="secureCouple";
        static void save(Activity context,String name,String value){try{SecretKey key=key();Cipher cipher=Cipher.getInstance("AES/GCM/NoPadding");cipher.init(Cipher.ENCRYPT_MODE,key);byte[] ciphertext=cipher.doFinal(value.getBytes(StandardCharsets.UTF_8));context.getSharedPreferences(PREF,Context.MODE_PRIVATE).edit().putString(name,Base64.getEncoder().encodeToString(ciphertext)).putString(name+".iv",Base64.getEncoder().encodeToString(cipher.getIV())).apply();}catch(Exception ignored){}}
        static String read(Activity context,String name){try{SharedPreferences preferences=context.getSharedPreferences(PREF,Context.MODE_PRIVATE);String encrypted=preferences.getString(name,null),iv=preferences.getString(name+".iv",null);if(encrypted==null||iv==null)return null;Cipher cipher=Cipher.getInstance("AES/GCM/NoPadding");cipher.init(Cipher.DECRYPT_MODE,key(),new javax.crypto.spec.GCMParameterSpec(128,Base64.getDecoder().decode(iv)));return new String(cipher.doFinal(Base64.getDecoder().decode(encrypted)),StandardCharsets.UTF_8);}catch(Exception error){return null;}}
        static SecretKey key()throws Exception{KeyStore store=KeyStore.getInstance("AndroidKeyStore");store.load(null);if(!store.containsAlias(KEY)){KeyGenerator generator=KeyGenerator.getInstance(KeyProperties.KEY_ALGORITHM_AES,"AndroidKeyStore");generator.init(new KeyGenParameterSpec.Builder(KEY,KeyProperties.PURPOSE_ENCRYPT|KeyProperties.PURPOSE_DECRYPT).setBlockModes(KeyProperties.BLOCK_MODE_GCM).setEncryptionPaddings(KeyProperties.ENCRYPTION_PADDING_NONE).build());generator.generateKey();}return ((KeyStore.SecretKeyEntry)store.getEntry(KEY,null)).getSecretKey();}
    }
}
