Section "Module"
    Load "fbdevhw"
    Load "shadow"
EndSection

Section "Device"
    Identifier "Beyond VM framebuffer"
    Driver "fbdev"
    Option "fbdev" "/dev/fb0"
EndSection

Section "ServerFlags"
    Option "AutoAddDevices" "true"
EndSection
