plugins { id 'com.android.application' }

android {
    namespace 'technology.co.beyondimagination.beyondkitchen'
    compileSdk 37

    defaultConfig {
        applicationId 'technology.co.beyondimagination.beyondkitchen'
        minSdk 26
        targetSdk 37
        versionCode 1
        versionName '0.0.1'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    sourceSets {
        main.assets.srcDirs += file('../../beyond-kitchen/data')
    }
}
