#!/bin/sh
set -eu

case "${1:-}" in
  start)
    nft -f /etc/nftables.conf
    ;;
  stop)
    nft flush ruleset
    ;;
  restart)
    "$0" stop
    "$0" start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}" >&2
    exit 1
    ;;
esac
