<?php
require_once __DIR__ . '/../includes/ecosystem.php';
$appShell = true;
$pageTitle = 'Settings | Beyond French';
require __DIR__ . '/includes/header.php';
?>
<style>
#language-settings button{padding:16px;border:1px solid #d7e1f5;border-radius:16px;color:#10224b;background:#fff;font:inherit;font-weight:850;cursor:pointer}.settings-shell{max-width:760px;margin:0 auto;padding:30px 20px 110px}.settings-shell h1{font-size:clamp(2.5rem,7vw,4.5rem);letter-spacing:-.06em;line-height:.95;margin:8px 0}.settings-shell .lesson-card{margin-top:18px}.difficulty-picker{display:grid;grid-template-columns:repeat(3,1fr);gap:11px;margin-top:16px}.difficulty-choice{position:relative;min-height:230px;padding:0;border:1px solid #284d7c;border-radius:20px;overflow:hidden;background:#0d2345;color:#fff;font:inherit;text-align:left;cursor:pointer;isolation:isolate}.difficulty-choice img{position:absolute;z-index:0;inset:0;width:100%;height:100%;object-fit:cover;object-position:top;opacity:.78;transition:transform .22s ease,opacity .22s ease}.difficulty-choice:after{content:"";position:absolute;z-index:0;inset:0;background:linear-gradient(180deg,transparent 25%,rgba(3,12,29,.18) 45%,rgba(3,12,29,.96) 100%)}.difficulty-choice .choice-copy{position:absolute;z-index:1;left:14px;right:14px;bottom:14px;display:grid;gap:3px;text-shadow:0 2px 8px #000}.difficulty-choice strong{font-size:1rem}.difficulty-choice small{color:#dbeaff;font-weight:700;line-height:1.25}.difficulty-choice:hover img,.difficulty-choice:focus-visible img{transform:scale(1.05);opacity:1}.difficulty-choice.selected{border:3px solid #63a4ff;box-shadow:0 0 0 3px rgba(99,164,255,.22)}.difficulty-choice.selected:before{content:"Selected";position:absolute;z-index:2;top:10px;right:10px;padding:5px 8px;border-radius:999px;background:#1768ff;color:#fff;font-size:.65rem;font-weight:900}.difficulty-preview{display:grid;grid-template-columns:repeat(4,1fr);gap:8px;margin-top:16px}.difficulty-preview img{width:100%;aspect-ratio:1;object-fit:cover;object-position:top;border-radius:14px;border:1px solid #315d94}.settings-status{color:var(--muted);font-size:.85rem}@media(max-width:560px){.settings-shell{padding-left:18px;padding-right:18px}.difficulty-picker{grid-template-columns:1fr;gap:10px}.difficulty-choice{min-height:158px}.difficulty-choice img{object-position:center 23%}.difficulty-preview{grid-template-columns:repeat(2,1fr)}}
</style>
<section class="settings-shell"><span class="eyebrow">YOUR EXPERIENCE</span><h1>More</h1><p>Choose your difficulty and tutor style, or continue with French Quest.</p>
<div class="lesson-card"><h2>French Quest</h2><p>Practice through routes, story mode, and trivia challenges.</p><a class="button primary" href="<?= h($frenchBase) ?>game.php">Open French Quest</a></div>
<div class="lesson-card"><h2>Choose your tutor style</h2><p>Pick the character world that fits how you want to learn.</p><div class="difficulty-picker" id="difficulty-settings"><button class="difficulty-choice" data-difficulty="beginner" data-age="kids" data-tutor="louis" type="button"><img alt="Louis, the beginner guide"><span class="choice-copy"><strong>Beginner</strong><small>Friendly chibbi guides</small></span></button><button class="difficulty-choice" data-difficulty="intermediate" data-age="teen" data-tutor="jazzy" type="button"><img alt="Jazzy, the intermediate guide"><span class="choice-copy"><strong>Intermediate</strong><small>Teen and young-adult guides</small></span></button><button class="difficulty-choice" data-difficulty="advanced" data-age="adult" data-tutor="pablo" type="button"><img alt="Pablo, the advanced guide"><span class="choice-copy"><strong>Advanced</strong><small>Realistic conversation guides</small></span></button></div><div class="difficulty-preview" id="difficulty-preview"></div><p class="settings-status" id="difficulty-status" aria-live="polite">Your tutor team is saved on this device.</p></div>
</section>
<script>
const base='<?= h($frenchBase) ?>assets/images/tutors/',difficultyStatus=document.getElementById('difficulty-status'),preview=document.getElementById('difficulty-preview'),tutorNames=['louis','irie','jazzy','pablo'];
const read=(key)=>{try{return localStorage.getItem(key)}catch(error){return null}},write=(key,value)=>{try{localStorage.setItem(key,value)}catch(error){}};
const folderFor=(age)=>age==='kids'?'':age==='teen'?'high-school/':'advanced/';
const setDifficulty=(difficulty,age)=>{write('beyond-french.difficulty',difficulty);write('beyond-french.age',age);const folder=folderFor(age);document.querySelectorAll('[data-difficulty]').forEach(button=>{button.classList.toggle('selected',button.dataset.difficulty===difficulty);const image=button.querySelector('img');if(image)image.src=base+folder+button.dataset.tutor+'.jpg'});preview.innerHTML=tutorNames.map(name=>'<img src="'+base+folder+name+'.jpg" alt="'+name+' tutor">').join('');difficultyStatus.textContent=difficulty.charAt(0).toUpperCase()+difficulty.slice(1)+' tutor team selected.'};
document.querySelectorAll('[data-difficulty]').forEach(button=>button.addEventListener('click',()=>setDifficulty(button.dataset.difficulty,button.dataset.age)));setDifficulty(read('beyond-french.difficulty')||'beginner',read('beyond-french.age')||'kids');
</script>
<?php require __DIR__ . '/includes/footer.php'; ?>
