plugins {
    id 'com.android.application'
}

android {
    namespace 'technology.co.beyondimagination.beyondtv'
    compileSdk 37

    defaultConfig {
        applicationId 'technology.co.beyondimagination.beyondtv'
        minSdk 26
        targetSdk 37
        versionCode 110
        versionName '1.1.0'
    }

    buildTypes {
        release {
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    buildFeatures {
        buildConfig true
    }
}
