plugins { id 'com.android.application' }

android {
    namespace 'technology.co.beyondimagination.beyond1'
    compileSdk 37

    defaultConfig {
        applicationId 'technology.co.beyondimagination.beyond1'
        minSdk 26
        targetSdk 37
        versionCode 2
        versionName '0.5.1'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
