<?php
declare(strict_types=1);
require __DIR__ . '/includes/config.php'; require_login();
$user=bt_current_user(); if(!$user||($user['account_type']??'')!=='owner'){http_response_code(403);exit('Studio owner access required.');}
$record=bt_owned_consent_record(bt_current_user_id(),(int)($_GET['id']??0));
if(!$record){http_response_code(404);exit('Consent record not found.');}
$answers=json_decode((string)$record['attestations_json'],true)?:[];$pageTitle='Signed consent record — Beyond Tattoo';require __DIR__.'/includes/header.php';
?>
<main class="consent-shell"><a class="consent-back" href="consent-dashboard.php">← Consent records</a><section class="consent-panel"><span class="eyebrow">Signed procedure consent · <?=e($record['signed_at'])?> UTC</span><h1><?=e($record['client_name'])?></h1><div class="consent-summary"><b><?=e($record['studio_name'])?></b><span>Artist: <?=e($record['artist_name'])?></span><span>Procedure: <?=e($record['procedure_description'])?></span><span>Placement: <?=e($record['placement'])?></span><?php if($record['appointment_date']):?><span>Appointment: <?=e($record['appointment_date'])?></span><?php endif; ?></div><h2>Client acknowledgements</h2><ul><?php foreach(['adult'=>'Adult age confirmation','sober'=>'Not impaired','health_discussed'=>'Relevant health matters discussed with artist','risks'=>'Procedure and risks reviewed','aftercare'=>'Aftercare responsibility acknowledged','consent'=>'Voluntary procedure consent','privacy'=>'Consent record storage notice acknowledged'] as $key=>$label): if(!empty($answers[$key])):?><li><?=e($label)?></li><?php endif; endforeach;?></ul><h2>Captured signature</h2><img class="consent-record-signature" src="<?=e($record['client_signature'])?>" alt="Signature of <?=e($record['client_name'])?>"><p class="consent-small">Version <?=e($record['consent_version'])?> · Record fingerprint (SHA-256): <code><?=e($record['record_sha256'])?></code></p><button class="consent-button" onclick="window.print()">Print / Save as PDF</button></section></main>
<style>.consent-shell{max-width:760px;margin:auto;padding:32px 18px 80px;color:#f5f1e9}.consent-back{display:inline-block;color:#d2b47b;margin-bottom:24px}.consent-panel{background:#141414;border:1px solid #423b31;border-radius:18px;padding:22px;margin:18px 0}.consent-panel h1{font-size:clamp(2.2rem,8vw,3.5rem)}.eyebrow{color:#d2b47b}.consent-summary{display:grid;gap:10px;margin:22px 0;padding:17px;background:#1c1b19;border-radius:12px}.consent-record-signature{width:min(100%,380px);height:90px;object-fit:contain;background:#f9f6ef;border-radius:6px}.consent-button{border:1px solid #bd9d63;background:#b68b4c;color:#15110b;border-radius:10px;padding:13px 16px;font-weight:850;cursor:pointer}.consent-small{color:#bbb;line-height:1.6}@media print{body{background:#fff!important}.consent-shell,.consent-shell *{color:#111!important}.consent-panel,.consent-summary{background:#fff;border:1px solid #aaa}.consent-back,.consent-button{display:none}}</style>
<?php require __DIR__.'/includes/footer.php'; ?>
