<?php
declare(strict_types=1);
require __DIR__ . '/includes/config.php'; require_login();
$current=bt_current_user();if(!$current||empty($current['onboarding_complete']))redirect('onboarding.php');
$role=(string)$current['account_type'];$tattoos=$role==='client'?bt_list_tattoos(bt_current_user_id()):[];$artists=bt_list_artists();$jobs=$role==='artist'?bt_list_open_jobs():[];$metrics=$role==='owner'?bt_owner_metrics(bt_current_user_id()):[];
$pageTitle='Dashboard — Beyond Tattoo';require __DIR__.'/includes/header.php';$success=flash('success');$error=flash('error');
?>
<div class="app-shell"><header class="app-header"><div class="container app-header-inner"><a class="brand" href="dashboard.php"><img class="brand-icon" src="../assets/icons/beyond-tattoo-192.webp" alt=""><span>BEYOND <b>TATTOO</b></span></a><span class="role-badge"><?=e($role==='client'?'Canvas':($role==='owner'?'Studio owner':ucfirst($role)))?></span></div></header><main class="container dashboard"><?php if($success):?><div class="notice"><?=e($success)?></div><?php endif;?><?php if($error):?><div class="notice error-notice"><?=e($error)?></div><?php endif;?><div class="welcome-row"><div><span class="eyebrow"><?=$role==='owner'?'🏪 Studio command centre':($role==='artist'?'🎨 Artist workspace':'🖼️ Canvas workspace')?></span><h1 class="section-title"><?=$role==='owner'?'Run the shop, ': 'Welcome, '?><?=e($current['name']?:'Beyond member')?>.</h1><p class="section-copy"><?=$role==='owner'?'Your team, hiring pipeline, production-ready stencils and public studio presence in one owner workspace.':($role==='artist'?'Keep your profile current and review live studio opportunities.':'Plan tattoos, discover real artists, and keep a private healing journal.')?></p></div></div>
<?php if($role==='owner'):?>
<section class="studio-identity panel"><div><small>YOUR STUDIO</small><h2><?=e($current['studio_name']?:'Name your studio')?></h2><p><?=e($current['city']?:'Add your city and service area')?></p></div><a class="btn btn-secondary" href="onboarding.php">Edit studio profile</a></section>
<div class="metric-grid studio-metrics"><div class="panel"><small>Active openings</small><strong><?=(int)$metrics['open_jobs']?></strong><span>Hiring pipeline</span></div><div class="panel"><small>Invites sent</small><strong><?=(int)$metrics['invites']?></strong><span>Artist outreach</span></div><div class="panel"><small>Artists discovered</small><strong><?=(int)$metrics['listed_artists']?></strong><span>Beyond network</span></div></div>
<section class="studio-owner-grid">
  <a class="panel studio-owner-card studio-owner-card--team" href="hire-artists.php"><span>01 · TEAM</span><b>Build your artist roster.</b><p>Publish openings, review working artists and save direct invitations.</p><strong>Manage hiring →</strong></a>
  <a class="panel studio-owner-card studio-owner-card--library" href="stencils.php"><span>02 · PRODUCTION</span><b>Open the stencil library.</b><p>Browse transfer-ready collections and daily studio drops.</p><strong>Browse 55 stencils →</strong></a>
  <a class="panel studio-owner-card studio-owner-card--presence" href="studios.php"><span>03 · DISCOVERY</span><b>See the public studio floor.</b><p>Review how shops and artists appear to clients across Beyond Tattoo.</p><strong>Explore studios →</strong></a>
  <a class="panel studio-owner-card studio-owner-card--account" href="profile.php"><span>04 · BUSINESS</span><b>Keep the owner account current.</b><p>Manage the Beyond ID connected to your shop workspace.</p><strong>Open account →</strong></a>
</section>
<section class="panel studio-next"><div><span class="eyebrow">Studio toolkit</span><h2>Everything starts with the roster.</h2><p class="meta">Add your shop details, then invite the artists who represent your studio.</p></div><a class="btn btn-primary" href="hire-artists.php">Add your first artist →</a></section>
<?php elseif($role==='artist'):?>
<div class="dashboard-grid"><section class="panel"><h2>Open opportunities</h2><div class="plan"><?php foreach($jobs as $job):?><div class="task"><span><strong><?=e($job['title'])?></strong><br><small class="meta"><?=e($job['studio_name'])?> • <?=e($job['opportunity_type'])?></small></span></div><?php endforeach;?><?php if(!$jobs):?><p class="meta">No studio opportunities have been posted yet.</p><?php endif;?></div></section><aside class="panel"><h2>Your Tattoo profile</h2><p><?=e($current['styles']?:'Add your styles so studios know what you do.')?></p><p class="meta"><?=e($current['city'])?><?= $current['availability']?' • '.e($current['availability']):''?></p><a class="btn btn-primary" href="onboarding.php">Edit profile</a><a class="btn btn-secondary" style="margin-top:10px" href="stencil-editor.php">Open stencil editor</a></aside></div>
<?php else:?>
<div class="dashboard-grid"><section class="panel"><h2>Your tattoo journey</h2><div class="tattoo-grid"><?php foreach(array_slice($tattoos,0,2) as $tattoo):?><article class="tattoo-mini"><span class="status"><?=$tattoo['status']==='active'?'● Active healing':'✓ Healed'?></span><h3><?=e($tattoo['name'])?></h3><p class="meta">Day <?=(int)$tattoo['healing_day']?> of <?=(int)$tattoo['healing_days']?></p><div class="progress"><span style="width:<?=(int)$tattoo['progress']?>%"></span></div></article><?php endforeach;?><?php if(!$tattoos):?><article class="tattoo-mini"><span class="status">Start here</span><h3>Add your first tattoo</h3><p class="meta">Track healing from the day of your appointment.</p><a class="btn btn-primary" href="add-tattoo.php">Add tattoo</a></article><?php endif;?></div></section><aside class="panel"><h2>Ottawa artists</h2><div class="plan"><?php foreach(array_slice($artists,0,3) as $artist):?><a class="task" href="artist-profile.php?slug=<?=urlencode($artist['slug'])?>"><span><strong><?=e($artist['display_name'])?></strong><br><small class="meta"><?=e($artist['styles'])?></small></span><strong>›</strong></a><?php endforeach;?></div><a class="btn btn-secondary btn-block" href="studios.php">Explore studios</a></aside></div>
<?php endif;?></main><nav class="bottom-nav"><a class="active" href="dashboard.php"><span>⌂</span>Home</a><?php if($role==='owner'):?><a href="hire-artists.php"><span>◎</span>Team</a><?php elseif($role==='artist'):?><a href="onboarding.php"><span>🖼️</span>Profile</a><?php else:?><a href="my-tattoos.php"><span>🎨</span>Tattoos</a><?php endif;?><a href="studios.php"><span>📍</span>Studios</a><a href="<?=$role==='owner'?'stencils.php':'stencil-editor.php'?>"><span>◇</span><?=$role==='owner'?'Library':'Canvas'?></a><a href="profile.php"><span>👤</span>Account</a></nav></div>
<?php require __DIR__.'/includes/footer.php'; ?>
