<?php
declare(strict_types=1);
require __DIR__ . '/includes/config.php';
$pageTitle = 'Store — Beyond Tattoo';
require __DIR__ . '/includes/header.php';

$products = [
    ['name' => 'Practice Skin Sheets', 'tag' => 'Fake skin', 'copy' => 'Flexible silicone practice sheets for lining, packing, shading and repeatable drills.', 'details' => 'Starter-friendly sheets · multiple sizes planned', 'icon' => 'SKIN', 'tone' => 'violet'],
    ['name' => 'Stencil Transfer Paper', 'tag' => 'Transfer supplies', 'copy' => 'Thermal and hand-transfer paper options for clean, studio-ready stencil placement.', 'details' => 'US Letter and A4 formats planned', 'icon' => 'PAPER', 'tone' => 'gold'],
    ['name' => 'Practice Skin Roll', 'tag' => 'Fake skin', 'copy' => 'A larger practice surface for sleeves, composition studies and placement exercises.', 'details' => 'Roll and sheet formats planned', 'icon' => 'ROLL', 'tone' => 'violet'],
    ['name' => 'Studio Practice Kit', 'tag' => 'Artist kit', 'copy' => 'A focused bundle for artists building confidence before working on clients.', 'details' => 'Practice materials · stencil workflow guide', 'icon' => 'KIT', 'tone' => 'gold'],
];
?>
<div class="app-shell bt-store-page">
  <header class="app-header"><div class="container app-header-inner"><a class="brand" href="index.php"><span class="brand-badge">B</span><span>Beyond <b>Tattoo</b></span></a><nav class="nav-links" aria-label="Store navigation"><a href="stencils.php">Stencils</a><a href="tools.php">Tools</a><a class="active" href="store.php">Store</a><a href="../beyond-market/">Beyond Market</a></nav><a class="btn btn-secondary" href="index.php">Back to library</a></div></header>
  <main class="container dashboard">
    <section class="panel store-hero"><div><span class="eyebrow">Beyond Tattoo 0.2 · Beyond Market</span><h1 class="section-title">Practice before the appointment.</h1><p class="section-copy">A focused supply catalog for fake skin, transfer paper and tattoo practice products. We are preparing the first inventory release now.</p><div class="store-actions"><a class="btn btn-primary" href="../beyond-market/#tattoo-supply-store">Open Beyond Market</a><a class="btn btn-secondary" href="stencils.php">Browse stencils</a></div></div><div class="store-hero-mark" aria-hidden="true"><span>INK</span><b>SUPPLY</b></div></section>
    <section class="store-notice" aria-label="Store status"><strong>Catalog preview</strong><span>Products will link to live Beyond Market listings as stock, pricing and fulfillment are confirmed.</span></section>
    <section class="store-section"><div class="store-heading"><div><span class="eyebrow">Artist essentials</span><h2 class="section-title">Upcoming supply catalog</h2></div><span class="store-count"><?=count($products)?> planned products</span></div><div class="store-grid"><?php foreach ($products as $product): ?><article class="store-card tone-<?=e($product['tone'])?>"><div class="store-card-art"><span><?=e($product['icon'])?></span><small>BEYOND TATTOO</small></div><div class="store-card-copy"><span class="store-tag"><?=e($product['tag'])?></span><h3><?=e($product['name'])?></h3><p><?=e($product['copy'])?></p><small><?=e($product['details'])?></small><button class="btn btn-secondary" type="button" disabled>Coming soon</button></div></article><?php endforeach; ?></div></section>
    <section class="panel store-guidance"><div><span class="eyebrow">Safe practice workflow</span><h2>Built for training and preparation.</h2><p class="section-copy">Use practice skin and transfer supplies for technique drills, stencil testing and client-preview preparation. These products are for practice use; artists remain responsible for sanitation, sizing and local professional requirements.</p></div><a class="btn btn-secondary" href="../beyond-market/">See all Beyond Market products</a></section>
  </main>
</div>
<style>
.bt-store-page{min-height:100vh}.bt-store-page .app-header-inner{gap:18px}.bt-store-page .nav-links{display:flex;gap:16px;align-items:center;margin-left:auto}.bt-store-page .nav-links a{text-decoration:none}.bt-store-page .nav-links a.active{color:var(--bt20-violet);font-weight:800}.store-hero{display:grid;grid-template-columns:minmax(0,1fr) 230px;gap:28px;align-items:center;background:linear-gradient(135deg,#fff,#f0eafb);overflow:hidden}.store-hero .section-title{max-width:680px}.store-actions{display:flex;gap:10px;flex-wrap:wrap;margin-top:22px}.store-hero-mark{display:grid;place-items:center;aspect-ratio:1;border:1px solid #d9c9f3;border-radius:50%;background:radial-gradient(circle,#d9c9f3,#fff 66%);color:var(--bt20-violet);font-weight:900;letter-spacing:.12em}.store-hero-mark span{font-size:2.6rem}.store-hero-mark b{font-size:.8rem}.store-notice{display:flex;gap:12px;align-items:center;margin:18px 0;padding:14px 18px;border:1px solid #ead8ae;border-radius:14px;background:#fffaf0;color:var(--bt20-muted)}.store-notice strong{color:var(--bt20-gold);white-space:nowrap}.store-heading{display:flex;justify-content:space-between;align-items:end;gap:16px;margin:28px 0 16px}.store-heading h2{margin-top:5px}.store-count{color:var(--bt20-muted);font-size:.85rem}.store-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:16px}.store-card{overflow:hidden;border:1px solid var(--bt20-border);border-radius:18px;background:#fff;box-shadow:var(--bt20-shadow)}.store-card-art{display:grid;place-items:center;align-content:center;gap:9px;min-height:170px;background:linear-gradient(145deg,#211a2c,#6d3cc8);color:#fff}.store-card.tone-gold .store-card-art{background:linear-gradient(145deg,#312617,#b88732)}.store-card-art span{font-size:2.1rem;font-weight:900;letter-spacing:.08em}.store-card-art small{font-size:.62rem;letter-spacing:.2em}.store-card-copy{padding:17px}.store-tag{color:var(--bt20-violet);font-size:.7rem;font-weight:900;text-transform:uppercase}.store-card h3{margin:6px 0;font-size:1.12rem}.store-card p{min-height:4.2em;margin:0 0 12px;color:var(--bt20-muted);font-size:.84rem;line-height:1.5}.store-card-copy>small{display:block;min-height:2.5em;color:var(--bt20-muted);font-size:.72rem}.store-card .btn{width:100%;margin-top:15px;opacity:.75}.store-guidance{display:flex;justify-content:space-between;align-items:center;gap:24px;margin:28px 0}.store-guidance h2{margin:.4rem 0}.store-guidance .section-copy{max-width:760px}@media(max-width:1000px){.store-grid{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:760px){.bt-store-page .nav-links{display:none}.store-hero{grid-template-columns:1fr}.store-hero-mark{width:170px}.store-notice,.store-guidance{display:block}.store-notice strong{display:block;margin-bottom:5px}.store-guidance .btn{display:inline-block;margin-top:15px}.store-grid{grid-template-columns:1fr}.store-heading{display:block}.store-count{display:block;margin-top:7px}}
</style>
<?php require __DIR__ . '/includes/footer.php'; ?>
