NAME="Beyond OS Creator Edition"
VERSION="0.1"
ID="beyond-os"
ID_LIKE="ubuntu debian"
PRETTY_NAME="Beyond OS Desktop 0.1 (Creator Edition)"
HOME_URL="https://beyondimagination.co.technology/"
SUPPORT_URL="https://beyondimagination.co.technology/help-center.php"
