plugins { id 'com.android.application' }
android { namespace 'technology.co.beyondimagination.beyondfrench'; compileSdk 37
 defaultConfig { applicationId 'technology.co.beyondimagination.beyondfrench'; minSdk 26; targetSdk 37; versionCode 1; versionName '1.2.0' }
 buildTypes { release { minifyEnabled true; shrinkResources true; proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro' } }
 compileOptions { sourceCompatibility JavaVersion.VERSION_17; targetCompatibility JavaVersion.VERSION_17 }
}
