<?php
declare(strict_types=1);
require_once __DIR__ . '/includes/bootstrap.php';
require_once __DIR__ . '/includes/code-thinking.php';
$role = strtolower((string)($_SESSION['role'] ?? ''));
if (empty($_SESSION['user_id']) || !in_array($role, ['admin', 'super_admin'], true)) {
    http_response_code(empty($_SESSION['user_id']) ? 401 : 403);
    if (empty($_SESSION['user_id'])) { header('Location: /beyond-id/auth/login.php?required=1'); exit; }
    exit('Code Thinking is available to Beyond administrators only.');
}
$csrf = csrf_token();
$scriptDirectory = str_replace('\\', '/', dirname((string)($_SERVER['SCRIPT_NAME'] ?? '/code.php')));
$appBasePath = $scriptDirectory === '/' || $scriptDirectory === '.' ? '' : rtrim($scriptDirectory, '/');
?>
<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#08050f"><title>Jaguar Code Thinking · Admin</title>
<style>
:root{color-scheme:dark;--bg:#08050f;--panel:#120d1d;--line:rgba(210,152,255,.2);--text:#faf7ff;--muted:#aaa1b8;--purple:#b35cff;--pink:#f264cf}*{box-sizing:border-box}body{margin:0;background:radial-gradient(circle at 78% -10%,rgba(142,43,213,.3),transparent 34%),var(--bg);color:var(--text);font:14px/1.55 system-ui,-apple-system,"Segoe UI",sans-serif}.wrap{max-width:1120px;margin:auto;padding:26px 20px 60px}.top{display:flex;justify-content:space-between;gap:20px;align-items:center;border-bottom:1px solid var(--line);padding:0 0 20px}.top a{color:#e9d6ff}.kicker{color:#d79cff;font-size:11px;font-weight:800;letter-spacing:.14em;text-transform:uppercase}h1{margin:5px 0;font-size:clamp(28px,4vw,42px);letter-spacing:-.04em}.lede{color:var(--muted);max-width:720px}.grid{display:grid;grid-template-columns:minmax(270px,340px) 1fr;gap:16px;margin-top:22px}.card{border:1px solid var(--line);border-radius:17px;background:rgba(18,13,29,.88);padding:18px}.card h2{margin:0 0 12px;font-size:16px}.label{display:block;margin:15px 0 6px;color:#d6ccdf;font-size:11px;font-weight:800}.select,textarea,input{width:100%;border:1px solid var(--line);border-radius:10px;background:#0d0915;color:var(--text);padding:11px;font:inherit}.select{min-height:44px}.select:focus,textarea:focus,input:focus{outline:2px solid rgba(179,92,255,.3);border-color:var(--purple)}textarea{resize:vertical;min-height:96px}.task{min-height:145px}.buttons{display:flex;flex-wrap:wrap;gap:8px;margin-top:13px}.button{border:1px solid var(--line);border-radius:10px;background:#21152f;color:white;padding:10px 14px;font-weight:750;cursor:pointer}.button.primary{background:linear-gradient(110deg,#7840d5,#c34cce)}.button:disabled{opacity:.45;cursor:wait}.subtle{color:var(--muted);font-size:12px}.revision{overflow-wrap:anywhere;color:#d4b6ee;font:11px ui-monospace,monospace}.status{min-height:20px;color:#d9c6ea;font-size:12px;margin:10px 0}.output{white-space:pre-wrap;overflow:auto;max-height:52vh;min-height:190px;padding:15px;border:1px solid var(--line);border-radius:12px;background:#08060d;color:#f1eaf8;font:12px/1.6 ui-monospace,Consolas,monospace}.notes{display:grid;gap:9px}.note{border:1px solid var(--line);border-radius:11px;padding:11px}.note.stale{border-color:rgba(255,180,107,.4)}.note small{display:block;color:var(--muted);margin-top:4px}.note .buttons{margin-top:8px}.empty{padding:13px;border:1px dashed var(--line);border-radius:10px;color:var(--muted);font-size:12px}@media(max-width:760px){.grid{grid-template-columns:1fr}.top{align-items:flex-start}.output{max-height:60vh}}
</style></head><body><main class="wrap">
<header class="top"><div><div class="kicker">Beyond administrator workspace</div><h1>Jaguar Code Thinking</h1><div class="lede">Read project context, plan changes, and draft reviewable patches. This workspace does not apply patches or deploy.</div></div><a href="chat.php">Jaguar chat ↗</a></header>
<div class="grid"><section class="card"><h2>Project workspace</h2><label class="label" for="project">Authorized BIT project</label><select class="select" id="project"><option value="">Loading authorized projects…</option></select><div class="status" id="projectStatus" role="status"></div><div class="revision" id="revision"></div>
<label class="label" for="action">Thinking action</label><select class="select" id="action"><option value="read">Read and explain</option><option value="plan" selected>Plan a change</option><option value="patch">Draft a patch</option></select>
<label class="label" for="task">Question or requested change</label><textarea class="task" id="task" maxlength="6000" placeholder="Describe the outcome you want."></textarea>
<label class="label" for="files">Relevant project files (optional, one relative path per line)</label><textarea id="files" placeholder="ai/api/chat.php&#10;ai/includes/modes.php"></textarea>
<div class="buttons"><button class="button primary" id="run">Ask Jaguar</button><button class="button" id="checks">Run configured checks</button></div>
<p class="subtle">Project roots come from the server allowlist. Code Thinking reads files inside the selected checkout only. Configured checks are the only commands it can run.</p>
<h2 style="margin-top:24px">Project memory</h2><p class="subtle">Notes are private to this project and active only for the Git revision they cite. Edit a stale note to approve it for this revision, or remove it.</p>
<div class="notes" id="notes"></div><label class="label" for="noteText">Add a revision-linked decision</label><textarea id="noteText" maxlength="1000" placeholder="A project decision or confirmed architectural constraint"></textarea><label class="label" for="noteSource">Source file or decision reference</label><input id="noteSource" maxlength="240" placeholder="docs/architecture.md#section"><label class="subtle" style="display:flex;align-items:flex-start;gap:8px;margin-top:11px"><input id="shareNote" type="checkbox" style="width:auto;margin:2px 0 0"> Approve this architecture note for use in other BIT projects</label><button class="button" id="addNote" style="margin-top:9px">Save note for this revision</button><h3 style="margin:22px 0 8px;font-size:13px">BIT-wide approved architecture notes</h3><p class="subtle">Only notes explicitly approved by an administrator are shared. Stale notes are excluded from Jaguar context until reviewed.</p><div class="notes" id="sharedNotes"></div>
</section><section class="card"><h2>Review output</h2><p class="subtle">Every response should identify its source revision, affected files, assumptions, risks, and verification steps. Patch output is a draft diff for review.</p><div class="status" id="resultStatus" role="status">Select a project to begin.</div><pre class="output" id="output">Jaguar has not read a project yet.</pre></section></div>
</main><script>
(() => {
const api = <?=json_encode($appBasePath . '/api/code-thinking.php', JSON_UNESCAPED_SLASHES)?>;
const csrf = <?=json_encode($csrf)?>;
const project = document.getElementById('project'), projectStatus = document.getElementById('projectStatus'), revision = document.getElementById('revision'), notes = document.getElementById('notes'), output = document.getElementById('output'), resultStatus = document.getElementById('resultStatus');
let catalog = [], sharedCatalog = [], editingNoteId = '', editingScope = 'project';
async function call(body = null) { const response = await fetch(api, {method: body ? 'POST' : 'GET', credentials:'same-origin', cache:'no-store', headers: body ? {'Content-Type':'application/json','X-CSRF-Token':csrf} : {}, body: body ? JSON.stringify(body) : undefined}); const raw = await response.text(); let data; try { data=JSON.parse(raw); } catch { throw new Error(`Code Thinking returned an unexpected ${response.status} response. Refresh and try again.`); } if (!response.ok) throw new Error(data.error || 'Code Thinking is unavailable.'); return data; }
function activeProject(){ return catalog.find(item => item.id === project.value); }
function editNote(note,scope,stale){if(scope==='bit'&&note.source_project){project.value=note.source_project;selectProject();}editingNoteId=note.id;editingScope=scope;document.getElementById('noteText').value=note.text;document.getElementById('noteSource').value=note.source||'';document.getElementById('shareNote').checked=scope==='bit';document.getElementById('addNote').textContent=stale?'Review and update note':'Save note changes';document.getElementById('noteText').focus();}
function noteCard(note,scope,stale,label){const box=document.createElement('div');box.className='note'+(stale?' stale':'');const text=document.createElement('div');text.textContent=note.text;const meta=document.createElement('small');meta.textContent=`${label} · ${note.source||'No source reference'}${note.revision?' · '+note.revision.slice(0,12):''}`;box.append(text,meta);const controls=document.createElement('div');controls.className='buttons';const edit=document.createElement('button');edit.className='button';edit.textContent=stale?'Review and update':'Edit';edit.onclick=()=>editNote(note,scope,stale);controls.append(edit);const remove=document.createElement('button');remove.className='button';remove.textContent='Remove';remove.onclick=()=>saveNote('note_delete',note.id,scope);controls.append(remove);box.append(controls);return box;}
function renderNotes(){const item=activeProject();notes.replaceChildren();if(!item)return;(item.notes||[]).forEach(note=>notes.append(noteCard(note,'project',false,`Revision ${(item.revision||'').slice(0,12)}`)));(item.stale_notes||[]).forEach(note=>notes.append(noteCard(note,'project',true,'Stale revision')));if(!notes.childElementCount)notes.innerHTML='<div class="empty">No project memory notes yet.</div>';}
function renderSharedNotes(){const target=document.getElementById('sharedNotes');target.replaceChildren();for(const note of sharedCatalog){target.append(noteCard(note,'bit',!!note.stale,`${note.stale?'Stale':'Approved'} · ${note.source_label||'Source unavailable'} · ${note.revision?.slice(0,12)||''}`));}if(!target.childElementCount)target.innerHTML='<div class="empty">No approved BIT-wide notes.</div>';}
function selectProject(){const item=activeProject();revision.textContent=item?.revision?`Git revision: ${item.revision}`:'No Git revision available';projectStatus.textContent=item?`${item.checks} configured check${item.checks===1?'':'s'} · repository context stays within this project`:'';renderNotes();}
async function refresh(){try{const data=await call();catalog=data.projects||[];sharedCatalog=data.shared_notes||[];project.replaceChildren();for(const item of catalog){const option=document.createElement('option');option.value=item.id;option.textContent=item.label;project.append(option);}if(!catalog.length){project.innerHTML='<option value="">No authorized Git workspaces configured</option>';projectStatus.textContent='Set JAGUAR_CODE_PROJECTS_JSON on the server to allow specific BIT checkouts.';}selectProject();renderSharedNotes();}catch(error){projectStatus.textContent=error.message;project.replaceChildren();}}
async function saveNote(action,noteId='',scope=editingScope){const item=activeProject();if(!item)return;try{const data=await call({project:item.id,action,note_id:noteId,scope,share_bit_wide:document.getElementById('shareNote').checked,note:document.getElementById('noteText').value,source:document.getElementById('noteSource').value});if(scope==='project'){item.notes=data.notes||[];item.stale_notes=(item.stale_notes||[]).filter(note=>note.id!==noteId);}else{sharedCatalog=(data.notes||[]).map(note=>({...note,source_label:catalog.find(project=>project.id===note.source_project)?.label||'Unavailable project',stale:false}));}editingNoteId='';editingScope='project';document.getElementById('noteText').value='';document.getElementById('noteSource').value='';document.getElementById('shareNote').checked=false;document.getElementById('addNote').textContent='Save note for this revision';renderNotes();renderSharedNotes();projectStatus.textContent='Project memory updated for the current revision.';}catch(error){projectStatus.textContent=error.message;}}
project.addEventListener('change',selectProject);
document.getElementById('addNote').addEventListener('click',()=>saveNote(editingNoteId?'note_edit':'note_add',editingNoteId,editingNoteId?editingScope:(document.getElementById('shareNote').checked?'bit':'project')));
document.getElementById('run').addEventListener('click',async event=>{const item=activeProject(),task=document.getElementById('task').value.trim();if(!item||!task){resultStatus.textContent='Choose a project and describe the task first.';return;}const button=event.currentTarget;button.disabled=true;resultStatus.textContent='Reading the selected project context…';output.textContent='Jaguar is preparing a response…';try{const data=await call({project:item.id,action:document.getElementById('action').value,task,files:document.getElementById('files').value.split(/\r?\n/).map(s=>s.trim()).filter(Boolean)});resultStatus.textContent=`${data.action} · repository revision ${data.revision}`;output.textContent=`Context files: ${(data.context_files||[]).join(', ')||'README/instructions only'}\n\n${data.message}`;}catch(error){resultStatus.textContent=error.message;output.textContent='';}finally{button.disabled=false;}});
document.getElementById('checks').addEventListener('click',async event=>{const item=activeProject();if(!item)return;const button=event.currentTarget;button.disabled=true;resultStatus.textContent='Running configured project checks…';try{const data=await call({project:item.id,action:'check'});resultStatus.textContent=`Checks at ${data.revision} · ${data.results.filter(x=>x.ok).length}/${data.results.length} passed`;output.textContent=data.configured?data.results.map(check=>`${check.ok?'PASS':'FAIL'}  ${check.command}${check.timed_out?' (timed out)':''}\n${check.output}`).join('\n\n'):'No project checks are configured.';}catch(error){resultStatus.textContent=error.message;output.textContent='';}finally{button.disabled=false;}});
refresh();
})();
</script></body></html>
