<?php
declare(strict_types=1);
function space_lesson(string $title,string $focus,string $teaching,string $practice,string $concept,string $example,string $activity): array{
 return compact('title','focus','teaching','practice','concept','example','activity');
}
$academyConfig=[
 'slug'=>'beyond-space','title'=>'Beyond Space Academy','icon'=>'🚀','logo'=>'/beyond-space/beyond-space-v1/assets/img/beyond-space-logo.webp','tagline'=>'Cosmic learning campus','accent'=>'#635bff','base'=>'/beyond-space/academy.php','css'=>'/beyond-space/academy.css?v=20260730-1','headline'=>'Learn the universe by exploring it.','description'=>'Five complete astronomy modules with 50 narrated lessons, interactive mission labs, lesson checks, saved progress, and module exams. Module 1 is free for every explorer.','default_path'=>'cosmic-explorer','group_label'=>'explorer paths',
 'disclaimer'=>'Beyond Space Academy teaches evidence-based astronomy and space science. Astrology and horoscopes are offered separately for entertainment and personal reflection.',
 'paths'=>[
  'space-cadet'=>['title'=>'Space Cadet','ages'=>'Ages 8–11','icon'=>'🛰️','guide'=>'Clear explanations, visual models, short missions, and discovery challenges.'],
  'cosmic-explorer'=>['title'=>'Cosmic Explorer','ages'=>'Ages 12–14','icon'=>'🌠','guide'=>'Deeper concepts, interactive evidence, mission design, and explain-it-back practice.'],
  'teen-astronomer'=>['title'=>'Teen Astronomer','ages'=>'Ages 15–17','icon'=>'🔭','guide'=>'Scientific reasoning, data interpretation, engineering tradeoffs, and portfolio projects.'],
  'adult-explorer'=>['title'=>'Adult Explorer','ages'=>'Ages 18+','icon'=>'🌌','guide'=>'Accessible science for lifelong learning, observation, technology, and cosmic perspective.'],
 ],
 'tracks'=>[],
];
$spaceTracks=[
 ['title'=>'Solar System & Planetary Science','description'=>'Compare worlds, model orbits, investigate moons and small bodies, and plan a robotic mission.'],
 ['title'=>'Stars, Light & Galaxies','description'=>'Use light to study stars, trace stellar life cycles, and explore the structure of galaxies.'],
 ['title'=>'Spaceflight & Robotics','description'=>'Apply forces, orbits, navigation, life support, satellites, and mission engineering.'],
 ['title'=>'Astrobiology & Exoplanets','description'=>'Evaluate habitability, biosignatures, ocean worlds, exoplanets, and the search for life.'],
 ['title'=>'Cosmology & Extreme Space','description'=>'Explore spacetime, black holes, cosmic expansion, dark matter, and the history of the universe.'],
];
foreach(array_keys($academyConfig['paths']) as $path)$academyConfig['tracks'][$path]=$spaceTracks;
$academyConfig['rich_lessons']['*']['solar-system-planetary-science']=[
 space_lesson('A Solar System Built to Scale','Scale models','Distances and sizes in space differ by enormous factors. A useful model states its scale and keeps diameter and distance consistent.','Create a scale that turns one astronomical unit into one metre, then place Earth and Mars.','A model is useful because it preserves a chosen relationship, not because it includes every detail.','If 1 AU equals 1 metre, Earth is 1 metre from the Sun and Mars averages about 1.52 metres away.','scale'),
 space_lesson('The Sun: Our Local Star','Solar energy','The Sun contains almost all Solar System mass. Fusion in its core converts hydrogen into helium and releases energy that moves outward as radiation.','Trace energy from the solar core to light reaching Earth.','Gravity compresses the core enough for fusion; outward pressure and inward gravity keep the Sun stable.','Sunlight takes about eight minutes to cross the average Sun–Earth distance.','sun'),
 space_lesson('Rocky Worlds','Terrestrial planets','Mercury, Venus, Earth, and Mars have solid surfaces but very different atmospheres, temperatures, and geological histories.','Compare two rocky planets and identify the evidence behind one difference.','Similar starting materials can produce different worlds through size, atmosphere, water, impacts, and internal heat.','Venus is hotter than Mercury because its thick carbon-dioxide atmosphere traps heat efficiently.','world-compare'),
 space_lesson('The Gas Giants','Jupiter and Saturn','Jupiter and Saturn are dominated by hydrogen and helium, have deep atmospheres, ring systems, and large families of moons.','Design a probe measurement that could investigate a giant planet atmosphere.','A gas giant has no ordinary solid surface; pressure and temperature rise with depth.','Jupiter’s Great Red Spot is a long-lived atmospheric storm larger than Earth.','world-compare'),
 space_lesson('The Ice Giants','Uranus and Neptune','Uranus and Neptune contain larger proportions of water, ammonia, and methane-rich material than Jupiter and Saturn.','Explain why “ice giant” describes composition rather than a simple frozen surface.','Planet categories summarize composition and structure, but every world has distinct weather and history.','Methane absorbs red light and contributes to the blue appearance of both planets.','world-compare'),
 space_lesson('Dwarf Planets and Classification','Scientific classification','A dwarf planet orbits the Sun and is rounded by gravity but has not cleared its orbital neighbourhood.','Classify a fictional world using the formal criteria.','Scientific categories change when evidence and definitions improve; a category is a tool, not a ranking.','Pluto is geologically complex even though its classification changed in 2006.','classify'),
 space_lesson('Moons as Worlds','Natural satellites','Moons can have oceans, atmospheres, volcanoes, magnetic interactions, and evidence of active geology.','Rank Europa, Titan, and Enceladus for a chosen science mission.','A small body can be a complex world when tidal heating and chemistry provide energy.','Europa likely holds a global salty ocean beneath an icy crust.','moon-mission'),
 space_lesson('Asteroids, Comets, and Meteors','Small bodies','Asteroids are rocky or metallic bodies; comets are rich in volatile material; a meteor is the streak produced in an atmosphere.','Build a diagram connecting meteoroid, meteor, and meteorite.','Small bodies preserve clues from early Solar System formation and also create impact hazards.','A meteoroid becomes a meteor while glowing in an atmosphere and a meteorite if material reaches the ground.','classify'),
 space_lesson('Gravity Writes the Orbits','Orbital motion','An orbit is continuous free fall: gravity bends an object’s forward motion around another body. Elliptical orbits change speed and distance.','Predict what happens when an orbiting object gains or loses speed.','Objects do not need continuous thrust to remain in orbit, but they do need the right sideways velocity.','A satellite in low Earth orbit falls toward Earth while Earth’s curved surface falls away beneath it.','orbit'),
 space_lesson('Planetary Mission Design Lab','Scientific missions','A mission connects one answerable question to an instrument, destination, trajectory, power source, communication plan, and risk budget.','Draft a robotic mission with one question, three instruments, and one major tradeoff.','Successful exploration is focused: every kilogram, watt, minute, and dollar must support the mission goal.','A Europa flyby can sample many regions with less radiation exposure than a long-duration orbiter.','mission'),
];
$academyConfig['rich_lessons']['*']['stars-light-galaxies']=[
 space_lesson('Light Is Cosmic Information','Electromagnetic spectrum','Different wavelengths reveal temperature, composition, motion, magnetic fields, and hidden structures.','Match radio, infrared, visible, ultraviolet, X-ray, and gamma observations to useful targets.','Astronomy is largely the science of decoding light and other signals that reach our instruments.','Infrared observations can see through dust that blocks visible light.','spectrum'),
 space_lesson('Stars Are Born in Clouds','Star formation','Cold molecular clouds collapse into dense cores. A protostar forms, heats, and eventually begins hydrogen fusion.','Order the stages from cloud to main-sequence star.','Gravity builds a star; fusion marks the start of its long stable life.','The Orion Nebula contains gas, dust, young stars, and forming planetary systems.','star-life'),
 space_lesson('Reading a Star','Stellar properties','Colour relates to surface temperature, spectra reveal elements, brightness depends on luminosity and distance, and motion shifts spectral lines.','Use colour and spectral clues to compare two stars.','One observation rarely tells the whole story; astronomers combine measurements and models.','A blue star is generally hotter at its surface than a red star.','star-color'),
 space_lesson('Main-Sequence Fusion','Stellar stability','Main-sequence stars fuse hydrogen while pressure from hot plasma balances inward gravity. Mass controls temperature, brightness, and lifetime.','Predict which of two stars uses its fuel faster.','More massive stars have more fuel but burn it disproportionately faster.','The Sun has remained on the main sequence for about 4.6 billion years.','star-life'),
 space_lesson('The Future of Sun-like Stars','Low-mass evolution','A Sun-like star expands into a red giant, sheds outer layers, and leaves a dense white dwarf.','Build a lifecycle diagram for a low-mass star.','A star’s initial mass is the strongest predictor of its evolution.','The Sun will not explode as a core-collapse supernova.','star-life'),
 space_lesson('Massive Stars and Supernovae','High-mass evolution','Massive stars fuse successively heavier elements until the core can no longer release energy through fusion, triggering collapse and explosion.','Explain how supernovae distribute elements into space.','Many elements in planets and bodies were forged in stars or stellar explosions.','Core-collapse supernovae can leave neutron stars or black holes.','star-life'),
 space_lesson('Stellar Remnants','White dwarfs, neutron stars, black holes','Compact remnants pack mass into small volumes. Their gravity, rotation, magnetic fields, and surrounding matter reveal their presence.','Compare the evidence used to detect each remnant.','Black holes are observed through measurable effects, not imagined as cosmic vacuum cleaners.','Pulsars are rotating neutron stars whose beams sweep across Earth.','remnants'),
 space_lesson('Our Milky Way','Galactic structure','The Milky Way contains a disk, bulge, bar, spiral structure, halo, dark matter, gas, dust, and hundreds of billions of stars.','Locate the Solar System in a labelled Milky Way model.','We observe our galaxy from inside its disk, so mapping it requires multiple wavelengths and distance methods.','The Sun lies in the Orion Spur, far from the galactic centre.','galaxy'),
 space_lesson('A Universe of Galaxies','Galaxy diversity','Spiral, elliptical, and irregular galaxies reflect different histories of star formation, gas, interaction, and merger.','Classify sample galaxies by visible structure and state the uncertainty.','Appearance is evidence, but classification should not pretend every object fits perfectly.','Galaxy collisions can trigger star formation without individual stars usually colliding.','galaxy'),
 space_lesson('Cosmic Distance Ladder Project','Measuring distance','Parallax, standard candles, redshift, and other methods overlap to build a ladder from nearby stars to distant galaxies.','Create a one-page guide showing which distance method works at each scale.','Independent overlapping methods let astronomers check calibration and uncertainty.','Parallax measures the apparent shift of a nearby star as Earth moves around the Sun.','distance'),
];
$academyConfig['rich_lessons']['*']['spaceflight-robotics']=[
 space_lesson('Why Rockets Work','Rocket propulsion','A rocket accelerates exhaust backward and gains forward momentum. It works in vacuum because thrust does not require pushing against air.','Relate exhaust speed and propellant flow to thrust.','Rocket motion follows conservation of momentum and Newton’s third law.','A balloon moves when air escapes in the opposite direction.','rocket'),
 space_lesson('Forces During Launch','Newton’s laws','Thrust must overcome weight and drag, while acceleration changes as propellant is consumed. Structural loads and vibration shape the vehicle.','Draw a force diagram for liftoff and ascent.','Mission engineering begins by identifying forces, constraints, and changing mass.','A rocket begins rising when upward thrust exceeds downward weight and drag.','forces'),
 space_lesson('Staging and the Rocket Equation','Mass efficiency','Discarding empty tanks and engines reduces mass. The rocket equation shows why carrying propellant to carry more propellant becomes difficult.','Compare a single-stage and staged mission concept.','Small mass savings can create large mission benefits.','Multi-stage launch vehicles drop hardware that is no longer useful.','rocket'),
 space_lesson('Reaching and Changing Orbit','Orbital manoeuvres','A launch gives sideways velocity; burns change the orbit’s energy and shape. Transfer orbits trade time, fuel, and geometry.','Plan a simplified transfer from low Earth orbit to a higher orbit.','Burn direction matters: thrust along motion raises orbital energy, while opposite thrust lowers it.','A Hohmann transfer uses two carefully timed burns between circular orbits.','orbit'),
 space_lesson('Navigation and Communication','Deep-space operations','Missions use radio tracking, star sensors, inertial systems, clocks, and orbital models. Signal delay grows with distance.','Create a communication plan for Mars including delay and safe modes.','A distant spacecraft must handle many problems autonomously because commands are not instant.','A one-way Earth–Mars radio signal can take several to more than twenty minutes.','navigation'),
 space_lesson('Keeping Humans Alive','Life-support systems','Crewed missions must manage oxygen, carbon dioxide, water, food, temperature, pressure, waste, fire, and radiation.','Design a closed-loop water and air flow diagram.','Life support is a connected system; one failure can affect many others.','The International Space Station recycles much of its water.','life-support'),
 space_lesson('Satellites in Everyday Life','Satellite systems','Satellites support weather forecasting, navigation, communication, science, environmental monitoring, and disaster response.','Match a public need to orbit, sensor, power, and ground system.','A satellite is only one part of a service that also requires launch, control, data processing, and users.','Weather satellites combine multiple wavelengths to track clouds, moisture, temperature, and fires.','satellite'),
 space_lesson('Robots Before Humans','Robotic exploration','Flybys, orbiters, landers, rovers, aircraft, and sample-return missions offer different coverage, risk, and complexity.','Select a robotic architecture for a hazardous destination.','Mission form should follow the science question and environment.','A rover provides detailed local geology while an orbiter maps broad regions.','robot'),
 space_lesson('Human Factors and Ethics','Responsible exploration','Isolation, workload, communication, health, teamwork, debris, contamination, and international responsibilities affect mission design.','Write a crew and planetary-protection risk register.','Exploration is a human system as well as a technical system.','A strong mission plan includes psychological safety and responsible treatment of other worlds.','mission'),
 space_lesson('Capstone: Design a Space Mission','Systems engineering','Define the mission question, success criteria, spacecraft, instruments, trajectory, operations, risks, and public value.','Present a mission review with evidence and defend one engineering tradeoff.','A complete mission connects science, engineering, people, budget, time, and risk.','A smaller instrument suite may improve reliability and still answer the highest-priority question.','mission'),
];
$academyConfig['rich_lessons']['*']['astrobiology-exoplanets']=[
 space_lesson('What Does Life Need?','Habitability','Known life needs chemistry, energy, and an environment that allows complex reactions. Liquid water is useful but not a guarantee of life.','Separate requirements, helpful conditions, and assumptions.','Habitability describes possibility; inhabited requires evidence.','A dark ocean beneath ice could use chemical energy instead of sunlight.','habitability'),
 space_lesson('The Habitable Zone','Orbital climate','The circumstellar habitable zone is where surface liquid water might persist under suitable atmospheric conditions.','Compare two planets around different stars.','Distance from a star matters, but atmosphere, geology, rotation, and history also shape climate.','Venus and Mars show why location alone does not determine habitability.','habitable-zone'),
 space_lesson('Mars: Past and Present','Mars exploration','Valleys, minerals, sediments, ice, and rover observations show that ancient Mars had liquid water environments.','Build an evidence table for ancient habitability.','Evidence of a habitable environment is not evidence that life existed there.','Perseverance is caching samples selected for future laboratory study.','mars'),
 space_lesson('Ocean Worlds','Europa and Enceladus','Tidal heating may maintain salty oceans beneath ice. Plumes and surface chemistry offer possible ways to sample them.','Compare a plume fly-through with an ice-penetrating lander.','An ocean, chemistry, and energy make ocean moons high-priority astrobiology targets.','Cassini detected water-rich plumes erupting from Enceladus.','moon-mission'),
 space_lesson('Finding Exoplanets','Detection methods','Transits reveal periodic dimming; radial velocity detects stellar motion; imaging, microlensing, and timing reach other systems.','Identify which signal belongs to each method.','Most methods reveal a planet indirectly, so repeated signals and independent checks matter.','A transit can estimate planet size relative to its star.','exoplanet'),
 space_lesson('Reading Alien Atmospheres','Atmospheric spectra','During a transit, some starlight filters through an atmosphere. Spectra can suggest gases, clouds, temperature, and chemistry.','Interpret a simplified transmission spectrum.','One molecule rarely proves life; context and combinations of gases matter.','Water vapour can be scientifically exciting without being a biosignature by itself.','spectrum'),
 space_lesson('Extremophiles on Earth','Life at limits','Earth organisms live in acidic, salty, cold, hot, dry, pressurized, and radiation-rich environments. They expand—but do not remove—the limits we consider.','Connect an extremophile to an extraterrestrial analogue.','Earth is our only confirmed example of life, so conclusions must keep that limitation visible.','Microbes near hydrothermal vents use chemical energy without sunlight.','habitability'),
 space_lesson('Listening and Looking for Technology','Technosignatures','Searches examine unusual radio or optical signals, atmospheric pollution, waste heat, and other possible technology signatures.','Design criteria that separate a candidate signal from interference.','Extraordinary claims require repeatable observations and careful elimination of ordinary explanations.','A signal that does not repeat cannot yet support a strong conclusion.','signal'),
 space_lesson('Planetary Protection','Responsible astrobiology','Forward contamination could harm another environment or confuse life-detection results; backward contamination requires safe sample handling.','Create a cleanliness and containment plan.','Protecting scientific integrity and environments is part of exploration.','Spacecraft for sensitive destinations undergo strict biological cleanliness controls.','protection'),
 space_lesson('Capstone: Evidence for Life Brief','Scientific argument','A strong claim connects observations to reasoning, alternatives, uncertainty, and the next test needed.','Write a mission briefing that ranks three possible biosignatures without overstating them.','Science advances through testable claims and transparent uncertainty, not certainty theatre.','A gas combination may be intriguing while geology remains a plausible alternative.','evidence'),
];
$academyConfig['rich_lessons']['*']['cosmology-extreme-space']=[
 space_lesson('The Observable Universe','Cosmic horizons','Light travels at a finite speed, so distant observations show the past. Expansion affects how far visible matter is now.','Build a timeline from nearby Moon light to ancient galaxy light.','The observable universe is the region from which signals have had time to reach us, not necessarily the whole universe.','We see the Sun about eight minutes in the past.','distance'),
 space_lesson('Gravity as Geometry','Spacetime','General relativity describes mass and energy curving spacetime, while objects follow the resulting paths.','Compare Newton’s useful approximation with a relativistic case.','Models can be valid in different ranges; deeper theory does not make every simpler model useless.','GPS timing requires relativistic corrections.','gravity'),
 space_lesson('An Expanding Universe','Cosmic expansion','On large scales, distant galaxies generally recede faster with greater distance as space expands. Bound systems do not simply stretch with it.','Plot a simplified distance–recession relationship.','Expansion is not an explosion from a central point into empty space.','Every large-scale observer sees other distant galaxies receding.','expansion'),
 space_lesson('Evidence for the Hot Big Bang','Cosmic history','Expansion, the cosmic microwave background, and primordial element abundances support a hot, dense early universe.','Match each observation to the prediction it supports.','The Big Bang model describes cosmic evolution from an early hot state, not what caused existence.','The cosmic microwave background is cooled relic radiation from the early universe.','evidence'),
 space_lesson('Dark Matter','Invisible mass','Galaxy rotation, gravitational lensing, clusters, and cosmic structure indicate more gravitating matter than visible material provides.','Compare competing explanations and identify the measurement each must fit.','Dark matter is inferred from multiple independent gravitational effects.','Lensing maps mass even when that mass emits little or no light.','dark-matter'),
 space_lesson('Dark Energy','Accelerated expansion','Observations of distant supernovae and cosmic structure indicate that expansion is accelerating. The physical explanation remains an open problem.','Separate the observation from proposed explanations.','Naming an unknown effect does not mean its nature is understood.','Type Ia supernovae helped reveal accelerated expansion.','expansion'),
 space_lesson('Black Holes','Extreme gravity','Black holes have event horizons, can spin, merge, bend light, and power luminous accretion systems. Their mass is measured through effects on matter, light, and spacetime.','Distinguish the event horizon, accretion disk, and singularity concepts.','A black hole’s influence obeys gravity; from far away it pulls like any object of equal mass.','Gravitational-wave detectors have measured merging black holes.','black-hole'),
 space_lesson('Time, Speed, and Relativity','Relativistic time','Moving clocks and clocks in different gravitational fields can accumulate different elapsed times. Experiments and technology measure these effects.','Use a thought experiment to explain why simultaneity depends on the observer.','Relativity changes relationships between measurements while preserving physical laws.','Atomic clocks flown on aircraft show measurable timing differences.','gravity'),
 space_lesson('What Science Does Not Yet Know','Uncertainty and frontiers','Open questions include dark matter identity, dark energy, quantum gravity, early-universe physics, and conditions beyond the observable horizon.','Label statements as measured, inferred, hypothetical, or unknown.','Good science makes uncertainty visible and turns it into testable questions.','Different models can fit current data and require better observations to distinguish them.','evidence'),
 space_lesson('Capstone: Tell the Cosmic Story','Synthesis','A scientific cosmic story connects evidence across scale and time—from early expansion to atoms, stars, galaxies, planets, and observers.','Create an illustrated timeline citing at least five observations and two uncertainties.','Wonder grows stronger when imagination is anchored to evidence.','A complete timeline distinguishes direct measurement, inference, and open questions.','cosmic-story'),
];
$academyConfig['scripts']='<script src="/beyond-space/assets/js/learning-center.js?v=20260730-1" defer></script>';
require dirname(__DIR__).'/includes/learning-academy.php';
