<?php
declare(strict_types=1);
$academyConfig=[
 'slug'=>'beyond-math','title'=>'Beyond Math Academy','icon'=>'🧮','logo'=>'/beyond-math/assets/img/beyond-math-logo.webp','tagline'=>'Learning campus','accent'=>'#1768ff','base'=>'/beyond-math/academy.php','css'=>'/beyond-math/academy.css','headline'=>'Math that grows with every learner.','description'=>'Five modules with ten interactive lessons each, guided practice, lesson tests, and module exams. Module 1 is free for everyone.',
 'tracks'=>[
  'preschool'=>['Numbers & Counting','Shapes & Space','Adding & Taking Away','Measurement & Time','Patterns & Money'],
  'kids'=>['Number Sense','Operations','Fractions & Decimals','Geometry & Measurement','Data & Problem Solving'],
  'preteen'=>['Integers & Rational Numbers','Ratios, Rates & Percent','Introduction to Algebra','Geometry & Coordinate Space','Statistics & Probability'],
  'teen'=>['Algebra Foundations','Functions & Graphs','Geometry & Trigonometry','Statistics & Data Science','Precalculus'],
  'adult'=>['Everyday Math','Money, Budgets & Interest','Skill Refresh','Practical Measurement','Personal Learning Plan']
 ]
];
$academyConfig['scripts']='<script src="/beyond-math/assets/js/learning-center.js?v=2.3.3" defer></script><script src="/beyond-math/assets/js/app.js?v=2.3.3" defer></script>';
$academyConfig['rich_lessons']['kids']['number-sense']=[
 ['title'=>'Build Numbers with Place Value','focus'=>'Place value','teaching'=>'A digit’s position tells us how much it is worth. In 347, the 3 means 3 hundreds, the 4 means 4 tens, and the 7 means 7 ones.','concept'=>'Numbers are built from groups of hundreds, tens, and ones. Moving one place left makes a digit ten times as valuable.','example'=>'582 = 5 hundreds + 8 tens + 2 ones = 500 + 80 + 2.','practice'=>'Build the target number by changing its hundreds, tens, and ones.','activity'=>'place-value'],
 ['title'=>'Read and Write Whole Numbers','focus'=>'Number names','teaching'=>'Read the hundreds first, then the tens and ones. A zero holds an empty place.','concept'=>'The written name and the digits describe the same quantity.','example'=>'406 is read “four hundred six.” The zero shows there are no tens.','practice'=>'Match the number to the correct number name.','activity'=>'number-name'],
 ['title'=>'Compare Numbers','focus'=>'Greater than and less than','teaching'=>'Compare digits from left to right. The first place that is different tells which number is greater.','concept'=>'The symbols greater than and less than open toward the greater number. An equals sign means both values are the same.','example'=>'563 is greater than 536 because 6 tens is greater than 3 tens.','practice'=>'Choose the symbol that makes the comparison true.','activity'=>'compare'],
 ['title'=>'Order Numbers on a Number Line','focus'=>'Number lines','teaching'=>'Numbers increase as you move right and decrease as you move left. Equal spaces represent equal changes.','concept'=>'A number line turns number size and distance into something you can see.','example'=>'On a line from 0 to 100 marked by tens, 70 belongs at the seventh mark after zero.','practice'=>'Move the marker to the requested number.','activity'=>'number-line'],
 ['title'=>'Round to the Nearest Ten','focus'=>'Rounding','teaching'=>'Look at the ones digit. Zero through four rounds down; five through nine rounds up.','concept'=>'Rounding estimates a value while keeping it close to the original.','example'=>'67 rounds to 70 because 67 is closer to 70 than to 60.','practice'=>'Round the number to the nearest ten.','activity'=>'rounding'],
 ['title'=>'Find Number Patterns','focus'=>'Patterns','teaching'=>'A number pattern follows a repeatable rule such as add 3, subtract 5, or double.','concept'=>'Finding the rule lets you predict numbers that have not appeared yet.','example'=>'4, 8, 12, 16 follows “add 4,” so the next number is 20.','practice'=>'Find the rule and complete the sequence.','activity'=>'pattern'],
 ['title'=>'Break Numbers Apart','focus'=>'Expanded form','teaching'=>'Expanded form shows the value of every nonzero digit and makes mental math easier.','concept'=>'A number can be composed and decomposed without changing its value.','example'=>'729 = 700 + 20 + 9.','practice'=>'Choose the expanded form that matches the number.','activity'=>'expanded'],
 ['title'=>'Estimate Quantities','focus'=>'Estimation','teaching'=>'An estimate is a sensible answer close to the exact amount. Use benchmarks and friendly numbers.','concept'=>'Good estimates are quick, reasonable, and useful for checking exact answers.','example'=>'A jar with about 5 rows of 10 buttons holds about 50 buttons.','practice'=>'Choose the most reasonable estimate.','activity'=>'estimate'],
 ['title'=>'Solve Number Sense Stories','focus'=>'Real-life reasoning','teaching'=>'Read the story, identify what is known, and decide whether you need an exact answer or an estimate.','concept'=>'Number sense helps you choose a strategy instead of reaching for an operation too quickly.','example'=>'If 198 people attend, about 200 is useful for planning chairs; 198 is needed for an exact count.','practice'=>'Choose the answer that makes sense in the story.','activity'=>'story'],
 ['title'=>'Number Sense Challenge Lab','focus'=>'Mastery','teaching'=>'Combine place value, comparison, rounding, patterns, and estimation to solve a multi-step challenge.','concept'=>'Strong number sense means moving flexibly between different representations and strategies.','example'=>'To estimate 398 + 403, round both numbers to 400, then add to get about 800.','practice'=>'Complete the final number mission.','activity'=>'mission']
];
require dirname(__DIR__).'/includes/learning-academy.php';
