<?php
declare(strict_types=1);require __DIR__.'/bootstrap.php';require_once dirname(__DIR__,3).'/config/bootstrap.php';
$msg='';$err='';$file=beyond_private_root().'/config/live.php';$cfg=beyond_live_config();
if (empty($_SESSION['verse_generator_csrf'])) {
  $_SESSION['verse_generator_csrf'] = bin2hex(random_bytes(32));
}
function setpath(array &$a,array $parts,$value):void{$r=&$a;foreach($parts as $i=>$p){if($i===count($parts)-1){$r[$p]=$value;return;}if(!isset($r[$p])||!is_array($r[$p]))$r[$p]=[];$r=&$r[$p];}}
if($_SERVER['REQUEST_METHOD']==='POST'){
 if(!Auth::verifyCsrf($_POST['csrf']??'')){$err='Invalid security token.';}else try{
  $provider=in_array($_POST['provider']??'', ['openai','elevenlabs'],true)?$_POST['provider']:'elevenlabs';setpath($cfg,['voice','provider'],$provider);
  foreach(['openai','elevenlabs'] as $p){$key=trim((string)($_POST[$p.'_api_key']??''));if($key!=='')setpath($cfg,['narration',$p,'api_key'],$key);}
  $elevenLabsKey=trim((string)($_POST['elevenlabs_api_key']??''));
  if($elevenLabsKey!=='')setpath($cfg,['voice','api_key'],$elevenLabsKey);
  setpath($cfg,['narration','openai','model'],trim((string)($_POST['openai_model']??'gpt-4o-mini-tts')));
  setpath($cfg,['narration','elevenlabs','model'],trim((string)($_POST['elevenlabs_model']??'eleven_v3')));
  setpath($cfg,['voice','model_id'],trim((string)($_POST['elevenlabs_model']??'eleven_v3')));
  $azureImageKey=trim((string)($_POST['azure_image_api_key']??''));
  if($azureImageKey!=='')setpath($cfg,['ai','azure_image','api_key'],$azureImageKey);
  setpath($cfg,['ai','azure_image','endpoint'],rtrim(trim((string)($_POST['azure_image_endpoint']??'')),'/'));
  setpath($cfg,['ai','azure_image','model'],trim((string)($_POST['azure_image_model']??'MAI-Image-2.5')));
  $azureTranslatorKey=trim((string)($_POST['azure_translator_api_key']??''));
  if($azureTranslatorKey!=='')setpath($cfg,['ai','azure_translator','api_key'],$azureTranslatorKey);
  setpath($cfg,['ai','azure_translator','endpoint'],rtrim(trim((string)($_POST['azure_translator_endpoint']??'https://api.cognitive.microsofttranslator.com')),'/'));
  setpath($cfg,['ai','azure_translator','region'],trim((string)($_POST['azure_translator_region']??'')));
  setpath($cfg,['voice','openai_voice'],trim((string)($_POST['openai_voice']??'coral')));
  // Saving an empty field deliberately clears its override. The runtime can
  // then select a language-verified voice instead of trapping the locale on
  // an old or accidentally shared ID.
  foreach(['en-US','fr-FR','fr-CA','es-ES','he-IL','ar-SA','it-IT','de-DE','ru-RU','pt-PT','ht-HT','en-JM','ln-CD'] as $loc){$v=trim((string)($_POST['voice_'.str_replace('-','_',$loc)]??''));setpath($cfg,['narration','elevenlabs','voices',$loc],$v);setpath($cfg,['voice','voices',$loc],$v);}
  $pabloVoice=trim((string)($_POST['character_voice_pablo']??'00uevfcKk0GtPlbU69ZH'));
  setpath($cfg,['narration','elevenlabs','character_voices','pablo'],$pabloVoice);
  $jazzyVoice=trim((string)($_POST['character_voice_jazzy']??'ELf3eScSrJr0jn1jDw8T'));
  setpath($cfg,['narration','elevenlabs','character_voices','jazzy'],$jazzyVoice);
  $irieVoice=trim((string)($_POST['character_voice_irie']??'RRIjxt3K1iKEkfsLGRXU'));
  setpath($cfg,['narration','elevenlabs','character_voices','irie'],$irieVoice);
  $php="<?php\ndeclare(strict_types=1);\n/* Protected live configuration. Keep beside public_html. */\nreturn ".var_export($cfg,true).";\n";$tmp=$file.'.tmp';if(file_put_contents($tmp,$php,LOCK_EX)===false||!rename($tmp,$file))throw new RuntimeException('Could not update protected configuration.');@chmod($file,0600);$msg='Premium voice settings saved.';
 }catch(Throwable $e){$err=$e->getMessage();}
}
require dirname(__DIR__).'/_header.php';?>
<link rel="stylesheet" href="/server/admin/daily-studio/studio.css"><link rel="stylesheet" href="/server/admin/daily-studio/studio-sunset.css"><div class="studio-head"><div><h1>Premium Voices</h1><p class="muted">Configure one shared narration provider for Daily Breath and Beyond French. API keys are stored in the protected var/config/live.php file.</p></div><a class="btn" href="/server/admin/daily-studio/">Back to Studio</a></div>
<?php if($msg):?><div class="alert studio-ok"><?=DailyStudio::esc($msg)?></div><?php endif;?><?php if($err):?><div class="alert" style="background:#4b0b1c;color:#ffd2dc"><?=DailyStudio::esc($err)?></div><?php endif;?>
<?php $activeProvider=(string)beyond_config('voice.provider','openai');if(!in_array($activeProvider,['openai','elevenlabs'],true))$activeProvider=beyond_config('narration.elevenlabs.api_key','')!==''?'elevenlabs':'openai'; ?>
<form method="post" class="card" autocomplete="off"><input type="hidden" name="csrf" value="<?=Auth::csrf()?>"><div class="field"><label>Active provider</label><select class="input" name="provider"><?php foreach(['elevenlabs'=>'ElevenLabs Premium','openai'=>'OpenAI Speech'] as $k=>$v):?><option value="<?=$k?>" <?=$k===$activeProvider?'selected':''?>><?=$v?></option><?php endforeach;?></select></div>
<div class="two"><div class="field"><label>ElevenLabs API key</label><input class="input" type="password" name="elevenlabs_api_key" value="<?=DailyStudio::esc((string)beyond_config('narration.elevenlabs.api_key',''))?>" autocomplete="off" placeholder="ElevenLabs API key"><small><?=beyond_config('narration.elevenlabs.api_key','')!==''?'Configured and prefilled':'Not configured'?></small></div><div class="field"><label>ElevenLabs model</label><input class="input" name="elevenlabs_model" value="<?=DailyStudio::esc((string)beyond_config('narration.elevenlabs.model','eleven_v3'))?>"></div></div><div style="margin:-6px 0 18px"><button class="btn" type="button" id="testElevenLabs">Test ElevenLabs connection</button><span id="elevenTestStatus" class="muted" style="margin-left:10px"></span></div>
<div class="two"><div class="field"><label>OpenAI API key</label><input class="input" type="password" name="openai_api_key" value="<?=DailyStudio::esc((string)beyond_config('narration.openai.api_key',''))?>" autocomplete="off" placeholder="OpenAI API key"><small><?=beyond_config('narration.openai.api_key','')!==''?'Configured and prefilled':'Not configured'?></small></div><div class="field"><label>OpenAI model / voice</label><input class="input" name="openai_model" value="<?=DailyStudio::esc((string)beyond_config('narration.openai.model','gpt-4o-mini-tts'))?>"><input class="input" style="margin-top:8px" name="openai_voice" value="<?=DailyStudio::esc((string)beyond_config('voice.openai_voice','coral'))?>" placeholder="coral"></div></div>
<h2>ElevenLabs voice IDs</h2><p class="muted">Choose the voices for each character. Pablo, Jazzy, and Irie have dedicated profiles separate from the general language settings. Use “Load account voices” to see available names and IDs; choosing an ID here does not generate audio.</p>
<?php $characterVoiceMap=['fr-FR'=>'Louis'];$frenchCharacterVoice=trim((string)beyond_config('narration.elevenlabs.voices.fr-FR',beyond_config('voice.voices.fr-FR','')));$pabloCharacterVoice=trim((string)beyond_config('narration.elevenlabs.character_voices.pablo','00uevfcKk0GtPlbU69ZH'));$jazzyCharacterVoice=trim((string)beyond_config('narration.elevenlabs.character_voices.jazzy','ELf3eScSrJr0jn1jDw8T'));$irieCharacterVoice=trim((string)beyond_config('narration.elevenlabs.character_voices.irie','RRIjxt3K1iKEkfsLGRXU'));$sharedCharacterVoice=$frenchCharacterVoice!==''&&$frenchCharacterVoice===$pabloCharacterVoice; ?>
<div id="characterVoiceWarning" class="alert" style="<?= $sharedCharacterVoice?'':'display:none;' ?>background:#4b0b1c;color:#ffd2dc;margin-bottom:16px">Louis and Pablo currently share one voice ID. Assign distinct character voices.</div>
<div style="margin:0 0 14px"><button class="btn" type="button" id="loadElevenLabsVoices">Load account voices</button><span id="elevenVoiceListStatus" class="muted" style="margin-left:10px"></span></div><datalist id="elevenLabsVoiceOptions"></datalist>
<div class="two"><div class="field"><label>Pablo · Mateo (Spanish character voice)</label><input class="input character-voice-id" data-character="Pablo" name="character_voice_pablo" value="<?=DailyStudio::esc($pabloCharacterVoice)?>" placeholder="ElevenLabs voice ID" list="elevenLabsVoiceOptions"><small>Mateo · Natural Male Spanish · <?=DailyStudio::esc($pabloCharacterVoice)?></small></div><div class="field"><label>Jazzy · Haitian Creole female voice</label><input class="input character-voice-id" data-character="Jazzy" name="character_voice_jazzy" value="<?=DailyStudio::esc($jazzyCharacterVoice)?>" placeholder="ElevenLabs voice ID" list="elevenLabsVoiceOptions"><small>Warm expressive female with an authentic Haitian Creole accent · <?=DailyStudio::esc($jazzyCharacterVoice)?></small></div><div class="field"><label>Irie · Annakay (Jamaican Patois character voice)</label><input class="input character-voice-id" data-character="Irie" name="character_voice_irie" value="<?=DailyStudio::esc($irieCharacterVoice)?>" placeholder="ElevenLabs voice ID" list="elevenLabsVoiceOptions"><small>Annakay · Warm expressive Jamaican female · <?=DailyStudio::esc($irieCharacterVoice)?></small></div><?php foreach(['en-US'=>'English','fr-FR'=>'French','fr-CA'=>'Canadian French','es-ES'=>'Spanish · general','he-IL'=>'Hebrew (Tanakh)','ar-SA'=>'Arabic (Quran)','it-IT'=>'Italian','de-DE'=>'German','ru-RU'=>'Russian','pt-PT'=>'Portuguese','ht-HT'=>'Haitian Kreyòl · general','en-JM'=>'Jamaican Patois · general','ln-CD'=>'Lingala (native-reviewed)'] as $loc=>$label):$current=beyond_config('narration.elevenlabs.voices.'.$loc,beyond_config('voice.voices.'.$loc,''));$character=$characterVoiceMap[$loc]??'';?><div class="field"><label><?=$character!==''?DailyStudio::esc($character.' · '):''?><?=$label?> (<?=$loc?>)</label><input class="input character-voice-id" <?=$character!==''?'data-character="'.DailyStudio::esc($character).'"':''?> data-locale="<?=$loc?>" name="voice_<?=str_replace('-','_',$loc)?>" value="<?=DailyStudio::esc(is_string($current)?$current:'')?>" placeholder="ElevenLabs voice ID" list="elevenLabsVoiceOptions"><?php if($character!==''):?><small>Dedicated character narrator profile</small><?php endif;?></div><?php endforeach;?></div>
<h2>Azure Translator</h2><p class="muted">Used by the Euro and Africa prerecorded banks. A global Translator resource needs only its key; regional and multi-service resources also need a region.</p><div class="two"><div class="field"><label>Translator key</label><input class="input" type="password" name="azure_translator_api_key" value="" autocomplete="new-password" placeholder="<?=beyond_config('ai.azure_translator.api_key','')!==''?'Configured — leave blank to keep':'Azure Translator key'?>"><small><?=beyond_config('ai.azure_translator.api_key','')!==''?'Configured securely':'Not configured'?></small></div><div class="field"><label>Translator region</label><input class="input" name="azure_translator_region" value="<?=DailyStudio::esc((string)beyond_config('ai.azure_translator.region',''))?>" placeholder="Blank or global for a global resource"></div></div><div class="field"><label>Translator endpoint</label><input class="input" name="azure_translator_endpoint" value="<?=DailyStudio::esc((string)beyond_config('ai.azure_translator.endpoint','https://api.cognitive.microsofttranslator.com'))?>"></div>
<h2 id="azure-game-assets">Azure game artwork</h2><p class="muted">These server-side credentials are used by Beyond Studio to generate FrenchQuest destination backgrounds. They are never embedded in the iOS app.</p><div class="two"><div class="field"><label>Azure image API key</label><input class="input" type="password" name="azure_image_api_key" value="" autocomplete="new-password" placeholder="<?=beyond_config('ai.azure_image.api_key','')!==''?'Configured — leave blank to keep':'Azure image API key'?>"><small><?=beyond_config('ai.azure_image.api_key','')!==''?'Configured securely':'Not configured'?></small></div><div class="field"><label>Azure Foundry endpoint</label><input class="input" name="azure_image_endpoint" value="<?=DailyStudio::esc((string)beyond_config('ai.azure_image.endpoint',''))?>" placeholder="https://your-resource.services.ai.azure.com"></div></div><div class="field"><label>Azure image deployment/model</label><input class="input" name="azure_image_model" value="<?=DailyStudio::esc((string)beyond_config('ai.azure_image.model','MAI-Image-2.5'))?>" placeholder="MAI-Image-2.5"></div><button class="btn" type="submit">Save premium voices and other services</button></form>
<script>
(()=>{const csrf='<?=DailyStudio::esc((string)($_SESSION['verse_generator_csrf']??''))?>';const requestVoices=async()=>{const r=await fetch('/beyond-id/admin/api/elevenlabs-test.php',{method:'POST',headers:{'X-CSRF-Token':csrf}});const d=await r.json();if(!r.ok)throw new Error(d.error||'Connection failed.');return d;};const b=document.getElementById('testElevenLabs'),s=document.getElementById('elevenTestStatus');if(b)b.addEventListener('click',async()=>{b.disabled=true;s.textContent='Testing…';try{const d=await requestVoices();s.textContent=d.message+' This checks your account only; it does not generate audio.';}catch(e){s.textContent=e.message||'Connection failed.';}finally{b.disabled=false;}});const load=document.getElementById('loadElevenLabsVoices'),listStatus=document.getElementById('elevenVoiceListStatus'),list=document.getElementById('elevenLabsVoiceOptions');if(load)load.addEventListener('click',async()=>{load.disabled=true;listStatus.textContent='Loading…';try{const d=await requestVoices();list.replaceChildren(...(d.voices||[]).map(v=>{const option=document.createElement('option');option.value=v.id;option.label=v.name+' · '+v.id;return option;}));listStatus.textContent=(d.voices||[]).length+' voices available. Type a voice name or ID to find it.';}catch(e){listStatus.textContent=e.message||'Could not load voices.';}finally{load.disabled=false;}});const chars=[...document.querySelectorAll('[data-character]')],warning=document.getElementById('characterVoiceWarning');const checkShared=()=>{const values=chars.map(el=>el.value.trim()).filter(Boolean);const same=new Set(values).size<values.length;if(warning){warning.style.display=same?'block':'none';if(same)warning.textContent='Two character profiles share one voice ID. Assign distinct voices to Louis, Pablo, Irie, and Jazzy.';}};chars.forEach(input=>input.addEventListener('input',checkShared));checkShared();})();
</script>
<?php require dirname(__DIR__).'/_footer.php';?>
