<?php
declare(strict_types=1);require __DIR__.'/bootstrap.php';require_once dirname(__DIR__,3).'/config/bootstrap.php';
$msg='';$err='';$file=beyond_private_root().'/config/live.php';$cfg=beyond_live_config();
if (empty($_SESSION['verse_generator_csrf'])) {
  $_SESSION['verse_generator_csrf'] = bin2hex(random_bytes(32));
}
function setpath(array &$a,array $parts,$value):void{$r=&$a;foreach($parts as $i=>$p){if($i===count($parts)-1){$r[$p]=$value;return;}if(!isset($r[$p])||!is_array($r[$p]))$r[$p]=[];$r=&$r[$p];}}
if($_SERVER['REQUEST_METHOD']==='POST'){
 if(!Auth::verifyCsrf($_POST['csrf']??'')){$err='Invalid security token.';}else try{
  $provider=in_array($_POST['provider']??'', ['openai','elevenlabs','azure'],true)?$_POST['provider']:'elevenlabs';setpath($cfg,['voice','provider'],$provider);
  foreach(['openai','elevenlabs','azure'] as $p){$key=trim((string)($_POST[$p.'_api_key']??''));if($key!=='')setpath($cfg,['narration',$p,'api_key'],$key);}
  $elevenLabsKey=trim((string)($_POST['elevenlabs_api_key']??''));
  if($elevenLabsKey!=='')setpath($cfg,['voice','api_key'],$elevenLabsKey);
  setpath($cfg,['narration','openai','model'],trim((string)($_POST['openai_model']??'gpt-4o-mini-tts')));
  setpath($cfg,['narration','elevenlabs','model'],trim((string)($_POST['elevenlabs_model']??'eleven_v3')));
  setpath($cfg,['voice','model_id'],trim((string)($_POST['elevenlabs_model']??'eleven_v3')));
  setpath($cfg,['narration','azure','region'],trim((string)($_POST['azure_region']??'')));
  $azureImageKey=trim((string)($_POST['azure_image_api_key']??''));
  if($azureImageKey!=='')setpath($cfg,['ai','azure_image','api_key'],$azureImageKey);
  setpath($cfg,['ai','azure_image','endpoint'],rtrim(trim((string)($_POST['azure_image_endpoint']??'')),'/'));
  setpath($cfg,['ai','azure_image','model'],trim((string)($_POST['azure_image_model']??'MAI-Image-2.5')));
  $azureTranslatorKey=trim((string)($_POST['azure_translator_api_key']??''));
  if($azureTranslatorKey!=='')setpath($cfg,['ai','azure_translator','api_key'],$azureTranslatorKey);
  setpath($cfg,['ai','azure_translator','endpoint'],rtrim(trim((string)($_POST['azure_translator_endpoint']??'https://api.cognitive.microsofttranslator.com')),'/'));
  setpath($cfg,['ai','azure_translator','region'],trim((string)($_POST['azure_translator_region']??'')));
  setpath($cfg,['voice','openai_voice'],trim((string)($_POST['openai_voice']??'coral')));
  foreach(['en-US','fr-FR','fr-CA','es-ES','ht-HT','en-JM','ln-CD'] as $loc){$v=trim((string)($_POST['voice_'.str_replace('-','_',$loc)]??''));if($v!==''){setpath($cfg,['narration','elevenlabs','voices',$loc],$v);setpath($cfg,['voice','voices',$loc],$v);}}
  foreach(['en-US','fr-FR','fr-CA','es-ES','it-IT','de-DE','ru-RU','pt-PT','ar-MA','ar-EG','sw-KE'] as $loc){$v=trim((string)($_POST['azure_voice_'.str_replace('-','_',$loc)]??''));if($v!=='')setpath($cfg,['narration','azure','voices',$loc],$v);}
  $php="<?php\ndeclare(strict_types=1);\n/* Protected live configuration. Keep beside public_html. */\nreturn ".var_export($cfg,true).";\n";$tmp=$file.'.tmp';if(file_put_contents($tmp,$php,LOCK_EX)===false||!rename($tmp,$file))throw new RuntimeException('Could not update protected configuration.');@chmod($file,0600);$msg='Premium voice settings saved.';
 }catch(Throwable $e){$err=$e->getMessage();}
}
require dirname(__DIR__).'/_header.php';?>
<link rel="stylesheet" href="/server/admin/daily-studio/studio.css"><link rel="stylesheet" href="/server/admin/daily-studio/studio-sunset.css"><div class="studio-head"><div><h1>Premium Voices</h1><p class="muted">Configure one shared narration provider for Daily Breath and Beyond French. API keys are stored in the protected var/config/live.php file.</p></div><a class="btn" href="/server/admin/daily-studio/">Back to Studio</a></div>
<?php if($msg):?><div class="alert studio-ok"><?=DailyStudio::esc($msg)?></div><?php endif;?><?php if($err):?><div class="alert" style="background:#4b0b1c;color:#ffd2dc"><?=DailyStudio::esc($err)?></div><?php endif;?>
<form method="post" class="card" autocomplete="off"><input type="hidden" name="csrf" value="<?=Auth::csrf()?>"><div class="field"><label>Active provider</label><select class="input" name="provider"><?php foreach(['openai'=>'OpenAI Speech','elevenlabs'=>'ElevenLabs Premium','azure'=>'Azure Speech'] as $k=>$v):?><option value="<?=$k?>" <?=$k===(string)beyond_config('voice.provider','openai')?'selected':''?>><?=$v?></option><?php endforeach;?></select></div>
<div class="two"><div class="field"><label>ElevenLabs API key</label><input class="input" type="password" name="elevenlabs_api_key" value="<?=DailyStudio::esc((string)beyond_config('narration.elevenlabs.api_key',''))?>" autocomplete="off" placeholder="ElevenLabs API key"><small><?=beyond_config('narration.elevenlabs.api_key','')!==''?'Configured and prefilled':'Not configured'?></small></div><div class="field"><label>ElevenLabs model</label><input class="input" name="elevenlabs_model" value="<?=DailyStudio::esc((string)beyond_config('narration.elevenlabs.model','eleven_v3'))?>"></div></div><div style="margin:-6px 0 18px"><button class="btn" type="button" id="testElevenLabs">Test ElevenLabs connection</button><span id="elevenTestStatus" class="muted" style="margin-left:10px"></span></div>
<div class="two"><div class="field"><label>OpenAI API key</label><input class="input" type="password" name="openai_api_key" value="<?=DailyStudio::esc((string)beyond_config('narration.openai.api_key',''))?>" autocomplete="off" placeholder="OpenAI API key"><small><?=beyond_config('narration.openai.api_key','')!==''?'Configured and prefilled':'Not configured'?></small></div><div class="field"><label>OpenAI model / voice</label><input class="input" name="openai_model" value="<?=DailyStudio::esc((string)beyond_config('narration.openai.model','gpt-4o-mini-tts'))?>"><input class="input" style="margin-top:8px" name="openai_voice" value="<?=DailyStudio::esc((string)beyond_config('voice.openai_voice','coral'))?>" placeholder="coral"></div></div>
<div class="two"><div class="field"><label>Azure Speech key</label><input class="input" type="password" name="azure_api_key" value="<?=DailyStudio::esc((string)beyond_config('narration.azure.api_key',''))?>" autocomplete="off" placeholder="Azure Speech key"><small><?=beyond_config('narration.azure.api_key','')!==''?'Configured and prefilled':'Not configured'?></small></div><div class="field"><label>Azure region</label><input class="input" name="azure_region" value="<?=DailyStudio::esc((string)beyond_config('narration.azure.region',''))?>" placeholder="canadacentral"></div></div><div style="margin:-6px 0 18px"><button class="btn" type="button" id="testAzure">Test Azure connection</button><span id="azureTestStatus" class="muted" style="margin-left:10px"></span></div>
<h2>ElevenLabs voice IDs</h2><div class="two"><?php foreach(['en-US'=>'English','fr-FR'=>'French','fr-CA'=>'Canadian French','es-ES'=>'Spanish','ht-HT'=>'Haitian Kreyòl','en-JM'=>'Jamaican Patois','ln-CD'=>'Lingala (native-reviewed)'] as $loc=>$label):$current=beyond_config('narration.elevenlabs.voices.'.$loc,beyond_config('voice.voices.'.$loc,''));?><div class="field"><label><?=$label?> (<?=$loc?>)</label><input class="input" name="voice_<?=str_replace('-','_',$loc)?>" value="<?=DailyStudio::esc(is_string($current)?$current:'')?>" placeholder="ElevenLabs voice ID"></div><?php endforeach;?></div>
<h2>Azure Speech voices</h2><p class="muted">Each supported language uses a native Azure speaker. Haitian Kreyòl, Jamaican Patois, and Lingala require matching ElevenLabs voice IDs above because Azure does not publish native voices for those locales.</p><div class="two"><?php $azureDefaults=['en-US'=>'en-US-JennyNeural','fr-FR'=>'fr-FR-DeniseNeural','fr-CA'=>'fr-CA-SylvieNeural','es-ES'=>'es-ES-ElviraNeural','it-IT'=>'it-IT-IsabellaNeural','de-DE'=>'de-DE-KatjaNeural','ru-RU'=>'ru-RU-SvetlanaNeural','pt-PT'=>'pt-PT-RaquelNeural','ar-MA'=>'ar-MA-MounaNeural','ar-EG'=>'ar-EG-ShakirNeural','sw-KE'=>'sw-KE-ZuriNeural'];foreach(['en-US'=>'English','fr-FR'=>'French','fr-CA'=>'Canadian French','es-ES'=>'Spanish','it-IT'=>'Italian','de-DE'=>'German','ru-RU'=>'Russian','pt-PT'=>'Portuguese','ar-MA'=>'Moroccan Arabic / Darija','ar-EG'=>'Egyptian Arabic','sw-KE'=>'Kiswahili (Kenya)'] as $loc=>$label):$current=beyond_config('narration.azure.voices.'.$loc,$azureDefaults[$loc]);if($loc!=='en-US'&&$current==='en-US-JennyMultilingualNeural')$current=$azureDefaults[$loc];if(is_array($current)){$first=array_key_first($current);$current=is_string($first)?$first:(string)reset($current);}?><div class="field"><label><?=$label?> (<?=$loc?>)</label><input class="input" name="azure_voice_<?=str_replace('-','_',$loc)?>" value="<?=DailyStudio::esc((string)$current)?>" placeholder="Azure voice name"></div><?php endforeach;?></div>
<h2>Azure Translator</h2><p class="muted">Used by the Euro and Africa prerecorded banks. A global Translator resource needs only its key; regional and multi-service resources also need a region.</p><div class="two"><div class="field"><label>Translator key</label><input class="input" type="password" name="azure_translator_api_key" value="" autocomplete="new-password" placeholder="<?=beyond_config('ai.azure_translator.api_key','')!==''?'Configured — leave blank to keep':'Azure Translator key'?>"><small><?=beyond_config('ai.azure_translator.api_key','')!==''?'Configured securely':'Not configured'?></small></div><div class="field"><label>Translator region</label><input class="input" name="azure_translator_region" value="<?=DailyStudio::esc((string)beyond_config('ai.azure_translator.region',''))?>" placeholder="Blank or global for a global resource"></div></div><div class="field"><label>Translator endpoint</label><input class="input" name="azure_translator_endpoint" value="<?=DailyStudio::esc((string)beyond_config('ai.azure_translator.endpoint','https://api.cognitive.microsofttranslator.com'))?>"></div>
<h2 id="azure-game-assets">Azure game artwork</h2><p class="muted">These server-side credentials are used by Beyond Studio to generate FrenchQuest destination backgrounds. They are never embedded in the iOS app.</p><div class="two"><div class="field"><label>Azure image API key</label><input class="input" type="password" name="azure_image_api_key" value="" autocomplete="new-password" placeholder="<?=beyond_config('ai.azure_image.api_key','')!==''?'Configured — leave blank to keep':'Azure image API key'?>"><small><?=beyond_config('ai.azure_image.api_key','')!==''?'Configured securely':'Not configured'?></small></div><div class="field"><label>Azure Foundry endpoint</label><input class="input" name="azure_image_endpoint" value="<?=DailyStudio::esc((string)beyond_config('ai.azure_image.endpoint',''))?>" placeholder="https://your-resource.services.ai.azure.com"></div></div><div class="field"><label>Azure image deployment/model</label><input class="input" name="azure_image_model" value="<?=DailyStudio::esc((string)beyond_config('ai.azure_image.model','MAI-Image-2.5'))?>" placeholder="MAI-Image-2.5"></div><button class="btn" type="submit">Save Azure asset settings</button></form>
<script>
(()=>{const b=document.getElementById('testElevenLabs'),s=document.getElementById('elevenTestStatus');if(!b)return;b.addEventListener('click',async()=>{b.disabled=true;s.textContent='Testing…';try{const r=await fetch('/beyond-id/admin/api/elevenlabs-test.php',{method:'POST',headers:{'X-CSRF-Token':'<?=DailyStudio::esc((string)($_SESSION['verse_generator_csrf']??''))?>'}});const d=await r.json();if(!r.ok)throw new Error(d.error||'Connection failed.');s.textContent=d.message;const voices=Array.isArray(d.voices)?d.voices:[];if(voices.length){document.querySelectorAll('input[placeholder="ElevenLabs voice ID"]').forEach(input=>{if(!input.value)input.value=voices[0].id;});s.textContent+=' Blank Voice ID fields were filled with '+voices[0].name+'. Save settings to keep them.';}}catch(e){s.textContent=e.message||'Connection failed.';}finally{b.disabled=false;}});})();
(()=>{const b=document.getElementById('testAzure'),s=document.getElementById('azureTestStatus');if(!b)return;b.addEventListener('click',async()=>{b.disabled=true;s.textContent='Testing…';try{const r=await fetch('/beyond-id/admin/api/azure-speech-test.php',{method:'POST',headers:{'X-CSRF-Token':'<?=DailyStudio::esc((string)($_SESSION['verse_generator_csrf']??''))?>'}});const d=await r.json();if(!r.ok)throw new Error(d.error||'Connection failed.');s.textContent=d.message}catch(e){s.textContent=e.message||'Connection failed.'}finally{b.disabled=false}})})();
</script>
<?php require dirname(__DIR__).'/_footer.php';?>
