<?php
declare(strict_types=1);
 $dailyHistoryFacts=require __DIR__.'/data/daily-history-facts.php';
function ancient_lesson(string $title,string $focus,string $teaching,string $practice,string $concept,string $example,string $activity): array{
 return compact('title','focus','teaching','practice','concept','example','activity');
}
$academyConfig=[
 'slug'=>'beyond-ancient','title'=>'Beyond Ancient Academy','icon'=>'🏺','tagline'=>'World history campus','accent'=>'#b06f2f','base'=>'/beyond-ancient/academy.php','css'=>'/beyond-ancient/academy.css?v=20260730-1','headline'=>'Read the evidence. Rebuild the past.','description'=>'Five world-history modules with 50 narrated lessons, artifact labs, source checks, saved progress, lesson assessments, and module exams. All modules are open for this investor demo.','default_path'=>'history-explorer','group_label'=>'historian paths',
 'demo_access'=>true,
 'daily_history_facts'=>$dailyHistoryFacts,
 'daily_fact_api'=>'/beyond-ancient/api/daily-history-fact.php',
 'scripts'=>"<script>(function(){fetch('/beyond-ancient/api/daily-history-fact.php',{headers:{Accept:'application/json'}}).then(function(r){return r.ok?r.json():null}).then(function(p){var f=p&&p.fact;if(!f)return;[['dailyHistoryNumber',f.number],['dailyHistoryTitle',f.title],['dailyHistoryFact',f.fact],['dailyHistoryLesson',f.lesson]].forEach(function(x){var e=document.getElementById(x[0]);if(e&&x[1]!=null)e.textContent=x[1]});[['dailyHistorySource',f.source_url],['dailyHistoryInstagram',f.instagram_url]].forEach(function(x){var e=document.getElementById(x[0]);if(e&&x[1]){e.href=x[1];e.hidden=false}});if(f.asset_url){var img=document.createElement('img');img.src=f.asset_url;img.alt=(f.title||'Daily History Fact')+' artwork';img.className='la-daily-fact-art';document.querySelector('.la-daily-fact>div').appendChild(img)}}).catch(function(){})})();</script>",
 'disclaimer'=>'Beyond Ancient distinguishes evidence, interpretation, tradition, and uncertainty. Human remains, sacred objects, and cultural heritage should be studied and represented with respect.',
 'paths'=>[
  'young-historian'=>['title'=>'Young Historian','ages'=>'Ages 9–12','icon'=>'🧭','guide'=>'Visual timelines, artifact clues, maps, stories, and short evidence challenges.'],
  'history-explorer'=>['title'=>'History Explorer','ages'=>'Ages 13–15','icon'=>'🏺','guide'=>'Source analysis, competing explanations, trade networks, and civilization projects.'],
  'teen-researcher'=>['title'=>'Teen Researcher','ages'=>'Ages 16–17','icon'=>'📜','guide'=>'Historical argument, archaeology, primary sources, ethics, and portfolio-ready research.'],
  'adult-learner'=>['title'=>'Adult Learner','ages'=>'Ages 18+','icon'=>'🏛️','guide'=>'Accessible global history with evidence, context, interpretation, and continued learning.'],
 ],
 'tracks'=>[],
];
$ancientTracks=[
 ['title'=>'Archaeology & Historical Evidence','description'=>'Learn how artifacts, sites, texts, landscapes, dates, and oral traditions help reconstruct the past.'],
 ['title'=>'Egypt, Nubia & the Nile','description'=>'Study Nile societies, belief, writing, state power, trade, daily life, and changing interpretations.'],
 ['title'=>'Mesopotamia, Levant & Persia','description'=>'Explore early cities, law, empires, trade, writing, belief, and cultural exchange across Southwest Asia.'],
 ['title'=>'Greece, Rome & the Mediterranean','description'=>'Compare citizenship, empire, philosophy, religion, labour, trade, and everyday life around the Mediterranean.'],
 ['title'=>'Ancient Africa, Asia & the Americas','description'=>'Investigate interconnected societies across Africa, South and East Asia, Oceania, and the Americas.'],
];
foreach(array_keys($academyConfig['paths']) as $path)$academyConfig['tracks'][$path]=$ancientTracks;
$academyConfig['rich_lessons']['*']['archaeology-historical-evidence']=[
 ancient_lesson('How We Know About the Past','Historical evidence','Historians combine written, material, environmental, visual, linguistic, and oral evidence. Every source was created in a context and answers some questions better than others.','Sort six sources by type and name one question each could help answer.','The past is gone, but evidence remains; history is a reasoned interpretation of that evidence.','A tax record may show quantities and names but reveal little about private beliefs.','source'),
 ancient_lesson('Context Before Conclusions','Provenience and context','An object’s location, layer, nearby materials, and relationship to a site often matter more than the object alone. Removing it without documentation destroys information.','Compare an artifact with and without excavation context.','Context turns an interesting object into historical evidence.','A coin found in a sealed floor layer can help date activity in that room.','context'),
 ancient_lesson('Layers of Time','Stratigraphy','In an undisturbed sequence, lower layers are generally older than those above them. Pits, rebuilding, erosion, and animal activity can complicate the pattern.','Order a site sequence and identify one disturbance.','Relative dating establishes before-and-after relationships without always giving calendar years.','A later grave cut can pass through older occupation layers.','layers'),
 ancient_lesson('Dating the Ancient World','Chronology','Archaeologists combine relative dating with radiocarbon dating, tree rings, inscriptions, coin sequences, and other methods. Each method has a range and uncertainty.','Choose a suitable dating method for wood, pottery style, and a stamped coin.','A date is an estimate supported by a method, sample, calibration, and uncertainty.','Radiocarbon dating measures radioactive carbon remaining in once-living material.','dating'),
 ancient_lesson('Reading Artifacts','Material culture','Material, manufacture, wear, repair, residue, and distribution help reveal how an object was made, used, valued, exchanged, and discarded.','Complete an observation–inference table for a replica vessel.','Observation describes what is present; inference explains what it may mean. Keep them separate.','Soot on a cooking pot supports heating use, while decoration alone does not prove elite ownership.','artifact'),
 ancient_lesson('Reading Written Sources','Textual criticism','A text has an author, audience, purpose, genre, transmission history, and point of view. Official inscriptions may advertise power; private letters may reveal daily concerns.','Annotate a short royal inscription for claims, audience, and missing voices.','A source can be biased and still be valuable evidence when read critically.','A victory monument may exaggerate success but accurately show how a ruler wanted to be seen.','source'),
 ancient_lesson('Maps, Landscapes & Environment','Historical geography','Rivers, soils, climate, routes, coastlines, resources, and human engineering shape possibilities without mechanically determining outcomes.','Explain two ways a landscape supported and constrained a settlement.','People adapt to environments and also transform them through irrigation, terraces, roads, and cities.','Nile flooding supported agriculture, while canals and administration helped distribute water.','map'),
 ancient_lesson('Oral Tradition and Memory','Oral history','Oral traditions preserve identity, genealogy, values, events, and place knowledge through performance and community memory. They require the same contextual care as written sources.','Compare what an oral account and an inscription can each contribute.','Writing is not the only reliable form of historical transmission.','Repeated community performance can preserve structured knowledge while details shift over time.','tradition'),
 ancient_lesson('Ownership, Repatriation & Ethics','Heritage ethics','Museums and researchers must consider acquisition history, descendant communities, sacred knowledge, human remains, looting, conservation, access, and repatriation.','Evaluate a museum label and propose questions about ownership and consent.','Studying the past creates responsibilities to living people and communities.','An object removed during colonial rule may be legally held yet ethically contested.','ethics'),
 ancient_lesson('Capstone: Build an Evidence Case','Historical argument','A strong historical claim uses multiple sources, explains context, considers alternatives, cites uncertainty, and avoids claiming more than evidence supports.','Create a digital exhibit with one claim, four sources, captions, and a limitations panel.','History is strongest when the reasoning between evidence and conclusion is visible.','Two sources that disagree can reveal competing interests rather than making research impossible.','evidence'),
];
$academyConfig['rich_lessons']['*']['egypt-nubia-the-nile']=[
 ancient_lesson('The Nile as a Connected World','River societies','The Nile linked communities across northeast Africa. Flood cycles, agriculture, boats, desert routes, and regional exchange shaped settlement without making history automatic.','Map river movement, farming zones, cataracts, and two trade routes.','Egypt and Nubia developed through both local traditions and long exchange.','Boats could travel north with the current and south with prevailing winds.','map'),
 ancient_lesson('Kingdoms and Chronology','Periodization','Historians organize long histories into periods such as Old, Middle, and New Kingdoms, but political unity and “intermediate” periods varied by region.','Build a timeline that includes continuity as well as dynastic change.','Period labels are research tools, not the lived experience of everyone.','A change of dynasty did not instantly change all village practices.','timeline'),
 ancient_lesson('Pharaoh, State & Administration','Political power','Rulers used administration, taxation, labour, temples, military force, diplomacy, and public imagery. Local officials and households also shaped how power worked.','Trace grain from harvest through storage, taxation, and redistribution.','States depend on systems and people, not only famous rulers.','Scribes recorded goods and labour that supported large institutions.','system'),
 ancient_lesson('Hieroglyphs and Writing','Writing systems','Egyptian writing included monumental hieroglyphs and cursive forms. Signs could represent sounds, words, and categories; literacy was specialized but writing appeared in many contexts.','Decode a simplified name using phonetic signs and determinatives.','Writing systems combine sound, meaning, material, and audience.','A determinative can clarify the category of a word without being pronounced.','writing'),
 ancient_lesson('Belief, Temples & the Afterlife','Religion and practice','Religious life included temples, household practices, festivals, offerings, local deities, royal ritual, and changing ideas about death and renewal.','Compare a temple scene, household object, and funerary text.','Ancient Egyptian religion was diverse and changed across more than three thousand years.','Funerary texts offered knowledge and protection, but access and form changed over time.','belief'),
 ancient_lesson('Pyramids, Tombs & Labour','Monument building','Monuments required quarrying, transport, surveying, food, skilled crews, seasonal labour, administration, and generations of accumulated knowledge.','Design a logistics board for moving stone and supporting workers.','Engineering achievements are social achievements involving many kinds of expertise.','Workers’ settlements provide evidence for organized crews, food production, and medical care.','engineering'),
 ancient_lesson('Daily Life Along the Nile','Households and work','Most people farmed, made goods, raised families, worshipped, traded, and navigated obligations within households and communities. Evidence varies by status, place, and time.','Reconstruct one day using tools, food remains, house plans, and texts.','Royal monuments are highly visible, but they represent only a small part of ancient life.','Bread and beer production left tools, installations, residues, and administrative records.','artifact'),
 ancient_lesson('Nubia, Kush & Regional Power','Nubian histories','Nubian societies controlled resources and routes, developed powerful kingdoms, built monuments, and sometimes ruled Egypt. Their histories should not be reduced to Egypt’s southern neighbour.','Compare Kerma, Napata, and Meroë using a continuity-and-change chart.','Regions influence one another without losing distinct identities.','Kushite rulers of Egypt formed the Twenty-fifth Dynasty while maintaining Nubian traditions.','compare'),
 ancient_lesson('Trade, Diplomacy & Empire','Interregional connections','Egyptian and Nubian states exchanged gold, ivory, cattle, timber, crafted goods, ideas, diplomats, hostages, and military force with neighbours.','Read a trade list and identify cooperation, inequality, and uncertainty.','Exchange can involve mutual benefit, coercion, cultural borrowing, and resistance at the same time.','Diplomatic letters reveal negotiation between rulers rather than simple isolation.','network'),
 ancient_lesson('Capstone: Curate a Nile Gallery','Museum interpretation','A responsible gallery balances rulers with workers, Egypt with Nubia, objects with context, and confidence with uncertainty.','Create six exhibit panels including one contested interpretation and one ethics note.','Curation shapes what visitors think matters; selection is an argument.','A gallery can pair a royal statue with workers’ tools and trade evidence to widen the story.','exhibit'),
];
$academyConfig['rich_lessons']['*']['mesopotamia-levant-persia']=[
 ancient_lesson('Rivers, Irrigation & Early Cities','Urban development','Communities between and around the Tigris and Euphrates built irrigation, farms, temples, workshops, and cities through cooperation, competition, and environmental adaptation.','Map water management and identify benefits and risks.','Cities emerge from linked economic, political, environmental, and social processes.','Canals supported crops but also required maintenance and could contribute to soil salinity.','map'),
 ancient_lesson('Cuneiform and Record Keeping','Writing and administration','Cuneiform began with accounting practices and developed across languages and genres on durable clay tablets.','Read a simplified tablet layout and separate quantities, people, and commodities.','Writing can grow from administrative needs and later support literature, law, science, and letters.','School tablets preserve exercises made by trainee scribes.','writing'),
 ancient_lesson('Temples, Palaces & Households','Institutions','Temples and palaces managed land, labour, goods, ritual, and political power, while households remained central economic and social units.','Diagram flows among farm, household, temple, market, and palace.','No single institution controlled every part of life across all cities and periods.','Ration lists illuminate institutional workers but not the entire population.','system'),
 ancient_lesson('Law, Justice & Social Difference','Legal evidence','Law collections, court records, contracts, and letters reveal ideals and disputes involving property, family, labour, debt, injury, and status.','Compare a public law statement with a court case.','A law code shows authorized principles, not proof that every case followed them exactly.','Different penalties in Hammurabi’s collection reflect unequal social status.','law'),
 ancient_lesson('Epic, Myth & Meaning','Literature','Works such as the Epic of Gilgamesh explore kingship, friendship, mortality, fame, loss, and human limits through stories transmitted and revised over time.','Identify a theme and support it with two moments from a summary.','Literature is evidence for ideas and values, not a literal report of every event.','Gilgamesh’s search for immortality frames reflection on what humans leave behind.','tradition'),
 ancient_lesson('Levantine Ports and Alphabets','Mediterranean exchange','Coastal cities connected inland and maritime networks. Alphabetic writing systems reduced the number of signs needed to represent speech and spread in varied forms.','Compare cuneiform, hieroglyphic, and alphabetic sign systems.','A simpler sign inventory does not make a culture or language simple.','Phoenician letter forms influenced later Greek and Latin alphabets.','network'),
 ancient_lesson('Assyria and Imperial Systems','Empire','Assyrian rulers combined armies, provincial administration, tribute, deportation, infrastructure, communication, scholarship, and intimidation. Subject peoples also negotiated and resisted.','Evaluate a palace relief beside an administrative letter.','Imperial images advertise control; administrative evidence reveals complexity and limits.','Royal reliefs emphasize victory while letters report logistical problems.','source'),
 ancient_lesson('Babylonian Knowledge','Mathematics and astronomy','Mesopotamian scholars recorded observations, calculated patterns, developed mathematical tables, and connected celestial events to learned traditions.','Use a base-sixty example to explain time measurement.','Ancient knowledge systems can combine accurate observation with cultural interpretation.','Base sixty remains visible in sixty minutes per hour and 360 degrees.','knowledge'),
 ancient_lesson('The Achaemenid Persian Empire','Imperial diversity','Persian rulers governed a vast, multilingual empire through satrapies, roads, tribute, local institutions, royal ideology, diplomacy, and military power.','Plan communication across an empire and identify where local autonomy helps.','Large empires often endure by combining central authority with regional practice.','The Royal Road supported communication across long distances.','network'),
 ancient_lesson('Capstone: Debate an Empire','Historical argument','Empire can be studied through infrastructure, violence, taxation, cultural exchange, local agency, and whose evidence survives.','Prepare a balanced case using one royal, one administrative, one archaeological, and one local source.','A strong evaluation can recognize achievements and harms without turning history into praise or condemnation alone.','Different source positions produce different experiences of the same empire.','evidence'),
];
$academyConfig['rich_lessons']['*']['greece-rome-the-mediterranean']=[
 ancient_lesson('A Connected Mediterranean','Maritime networks','Seas linked ports, islands, farms, colonies, markets, armies, migrants, enslaved people, pilgrims, and ideas. Geography created routes as well as hazards.','Trace a commodity from producer to port to consumer.','The Mediterranean was not one culture; it was a network of interacting societies.','Pottery distributions help map exchange when texts are limited.','network'),
 ancient_lesson('The Greek Polis','City-states','A polis joined an urban centre, territory, institutions, cults, and citizen community. Athens and Sparta were influential but not models for every Greek society.','Compare two poleis without treating either as typical.','Shared language and religious traditions did not erase political rivalry or regional diversity.','Citizenship rules excluded many residents, including women, foreigners, and enslaved people.','compare'),
 ancient_lesson('Athenian Democracy in Context','Citizenship and power','Athenian democracy used assemblies, councils, juries, selection by lot, and direct participation among eligible male citizens while relying on exclusion and slavery.','Map who could participate, who could not, and how decisions moved.','Democracy has a history; using the word does not make ancient and modern systems identical.','Selection by lot distributed many offices among citizens.','law'),
 ancient_lesson('Sparta Beyond the Legend','Evidence and myth','Spartan society involved citizen soldiers, women with distinctive property roles, dependent perioikoi, and exploited helots. Much surviving description comes from outsiders.','Rate claims about Sparta by source distance and purpose.','Famous reputations can grow from selective evidence and later admiration.','Athenian authors may reveal Sparta while also projecting their own concerns.','source'),
 ancient_lesson('Philosophy, Drama & Public Debate','Ideas in society','Philosophers, dramatists, teachers, and audiences debated ethics, knowledge, government, fate, persuasion, and civic responsibility in specific social contexts.','Stage a dialogue between two positions and cite the historical setting.','Ideas are produced through communities, institutions, conflict, and performance.','Tragedies could place moral and political dilemmas before large festival audiences.','tradition'),
 ancient_lesson('Alexander and Hellenistic Kingdoms','Conquest and exchange','Alexander’s campaigns broke the Achaemenid Empire, and successor kingdoms created new political centres, conflicts, migration, cultural exchange, and blended practices.','Follow one city through conquest, settlement, and local response.','Cultural interaction is not one-way; people adopt, adapt, reject, and combine practices.','Greek became a widespread administrative language alongside persistent local languages.','network'),
 ancient_lesson('The Roman Republic','Republican institutions','Assemblies, magistrates, the Senate, patronage, family networks, military service, and social conflict shaped Roman politics. Expansion altered the system.','Diagram a proposal moving through republican institutions.','Formal institutions and informal power operate together.','The Conflict of the Orders is remembered as a long struggle over rights and office.','system'),
 ancient_lesson('Empire, Provinces & Citizenship','Roman imperial rule','Roman emperors relied on armies, cities, governors, taxes, law, roads, local elites, and imperial cults. Provincial experience differed widely.','Compare imperial rule from a governor, merchant, soldier, and local family perspective.','An empire can integrate regions while producing unequal burdens and resistance.','Citizenship expanded over centuries and was granted broadly to free inhabitants in 212 CE.','compare'),
 ancient_lesson('Labour, Slavery & Daily Life','Social history','Roman society depended heavily on enslaved labour alongside farming, trade, military service, crafts, domestic work, and wage labour. Status, gender, wealth, and legal position shaped life chances.','Build a household case study without romanticizing slavery.','Architecture and art often show elite ideals; ordinary lives require broader evidence.','Graffiti, tools, rubbish, burials, and contracts reveal experiences missing from elite literature.','artifact'),
 ancient_lesson('Capstone: Build a Mediterranean City','Urban synthesis','A city model should connect water, food, housing, worship, work, government, defence, entertainment, trade, inequality, and waste.','Design a historically grounded city and explain five choices with evidence.','Cities are systems built and maintained by people with unequal power and resources.','An aqueduct matters only alongside distribution, maintenance, access, and drainage.','city'),
];
$academyConfig['rich_lessons']['*']['ancient-africa-asia-the-americas']=[
 ancient_lesson('Thinking Beyond a Single “Cradle”','Global comparison','Agriculture, urbanism, political complexity, writing, and monumentality developed in multiple regions through different sequences and local conditions.','Compare two regions without forcing them into one ladder of progress.','Difference is not delay; societies solve problems according to their own histories and environments.','A society can be complex without cities, kings, or writing.','compare'),
 ancient_lesson('Aksum and the Red Sea','Northeast African networks','Aksum connected highland agriculture, Red Sea trade, coinage, monumental building, inscriptions, and changing religious traditions.','Map links among the African interior, Arabia, and Mediterranean ports.','African states were active participants in long-distance exchange.','Aksumite coins communicate rulers, economy, language, and religious change.','network'),
 ancient_lesson('West African Cities and Exchange','Early West Africa','Long before later famous empires, communities developed farming, craft specialization, regional exchange, towns, and distinctive artistic traditions across varied environments.','Use settlement and material evidence to challenge “history begins with writing.”','Archaeology can recover complex histories where local written archives are limited.','Jenne-jeno provides evidence for early urbanism and specialized production in the Inland Niger Delta.','artifact'),
 ancient_lesson('Indus Cities and Infrastructure','South Asian urbanism','Indus cities used planned streets, drainage, standardized weights, craft production, and wide trade networks. Their script remains undeciphered.','Infer what infrastructure shows while marking what remains unknown.','Not knowing rulers’ names does not mean we know nothing about a society.','Standardized weights support evidence for coordinated exchange.','city'),
 ancient_lesson('Mauryan India and Ashoka','State and inscription','The Mauryan Empire connected diverse regions. Ashoka’s edicts used inscriptions in multiple languages and scripts to communicate ethical and administrative messages.','Compare two edicts by audience, location, and language.','Public inscriptions show imperial ideals and communication strategies, not every local response.','Rock and pillar edicts were placed along routes and in significant regions.','source'),
 ancient_lesson('Early Chinese States and Thought','China in antiquity','Shang and Zhou evidence includes cities, bronze production, oracle bones, ritual systems, warfare, kinship, and political ideas such as the Mandate of Heaven.','Connect an oracle-bone question to what it can and cannot reveal.','Political concepts can justify rule while also providing language for criticizing rulers.','The Mandate of Heaven framed legitimacy as conditional on moral order.','writing'),
 ancient_lesson('Qin and Han Systems','Unification and empire','Qin and Han governments used law, administration, roads, military systems, taxation, records, standardization, frontier relations, and court politics in different ways.','Evaluate one benefit and one cost of standardization.','Unification is an ongoing process, not a single event accomplished equally everywhere.','Standard measures aided administration and trade while state demands could be severe.','system'),
 ancient_lesson('Maya Cities, Time & Writing','Mesoamerican histories','Maya societies developed cities, dynasties, writing, mathematics, calendars, art, farming systems, and regional networks across many independent polities.','Read a monument as political communication rather than decoration alone.','The Maya were and are diverse peoples; ancient political change was not disappearance.','Long Count dates place recorded events in a precise historical chronology.','writing'),
 ancient_lesson('Andean Worlds and the Inka','Andean systems','Andean societies engineered terraces, roads, storage, textiles, raised fields, and political networks across extreme environments. The Inka built on earlier traditions.','Design a resource network across coast, valley, and highland zones.','Complex administration can operate through media other than alphabetic writing.','Khipu encoded structured information using cords, knots, colour, and position.','network'),
 ancient_lesson('Capstone: Global Ancient Worlds Atlas','Global synthesis','A responsible atlas centres regional evidence, avoids ranking civilizations, shows connections and independent developments, and includes living descendant communities.','Create five regional spreads with sources, maps, timelines, uncertainties, and heritage notes.','World history becomes clearer when comparison respects both shared human problems and distinct solutions.','Trade links regions, but similar inventions can also emerge independently.','exhibit'),
];
$academyConfig['scripts']='<script src="/beyond-ancient/assets/js/learning-center.js?v=20260730-1" defer></script>';
require dirname(__DIR__).'/includes/learning-academy.php';
