<?php
declare(strict_types=1);
require_once __DIR__ . '/../includes/ecosystem.php';
require_once __DIR__ . '/../config/bootstrap.php';
require_once __DIR__ . '/includes/web-app.php';
$pdo = beyond_db();
$date = (string)($_GET['date'] ?? date('Y-m-d'));
$tradition = dailybreath_faith_tradition((string)($_GET['tradition'] ?? 'bible'));
$locale = dailybreath_scripture_locale((string)($_GET['lang'] ?? $_SESSION['locale'] ?? 'en'));
if (!preg_match('/^\d{4}-\d{2}-\d{2}$/', $date) || !checkdate((int)substr($date,5,2),(int)substr($date,8,2),(int)substr($date,0,4))) { http_response_code(404); exit('Reading not found.'); }
$content = dailybreath_published_content($pdo, $date, $tradition, $locale);
if (!$content) { http_response_code(404); exit('This daily reading has not been published.'); }
function daily_share_e(mixed $value): string { return htmlspecialchars((string)$value, ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8'); }
$faithLabel = dailybreath_tradition_label($tradition);
$kind = $tradition === 'quran' ? 'Ayah' : ($tradition === 'torah' ? 'Passage' : 'Verse');
$imageName = $tradition === 'quran' ? 'quran' : ($tradition === 'torah' ? 'tanakh' : 'bible');
$useArtwork = (string)($content['theme'] ?? 'seasonal') === 'scripture';
$imagePath = $useArtwork ? '/dailybreath/assets/images/'.$imageName.'-forest-landscape.png' : '/dailybreath/assets/icons/dailybreath-mark-v2.png';
$cardBackground = $useArtwork ? "linear-gradient(#00130d22,#00130d72),url('".$imagePath."') center/cover no-repeat" : 'linear-gradient(145deg,#17472d,#061b12)';
$mobileBackground = $useArtwork ? "linear-gradient(#00130d25,#00130d78),url('/dailybreath/assets/images/".$imageName."-forest-portrait.png') center/cover no-repeat" : 'linear-gradient(145deg,#17472d,#061b12)';
$readerBook = trim((string)$content['reader_book']) ?: ($tradition === 'quran' ? '1' : 'Psalms');
$readerUrl = 'scripture.php?tradition='.rawurlencode($tradition).'&book='.rawurlencode($readerBook).'&chapter='.max(1,(int)$content['reader_chapter']).'#verse-'.max(1,(int)$content['reader_verse']);
$canonical = 'https://beyondimagination.co.technology/dailybreath/daily.php?date='.rawurlencode($date).'&tradition='.rawurlencode($tradition).'&lang='.rawurlencode($locale);
$pageTitle = $faithLabel.' '.$kind.' of the Day · '.(string)$content['reference'];
$description = function_exists('mb_substr') ? mb_substr((string)$content['passage'],0,240) : substr((string)$content['passage'],0,240);
$direction = $tradition === 'quran' && preg_match('/[\x{0600}-\x{06FF}]/u', (string)$content['passage']) ? 'rtl' : 'ltr';
?><!doctype html><html lang="<?=daily_share_e($locale)?>" dir="<?=daily_share_e($direction)?>"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#09271b"><title><?=daily_share_e($pageTitle)?> | Daily Breath</title><meta name="description" content="<?=daily_share_e($description)?>"><link rel="canonical" href="<?=daily_share_e($canonical)?>"><meta property="og:type" content="article"><meta property="og:title" content="<?=daily_share_e($pageTitle)?>"><meta property="og:description" content="<?=daily_share_e($description)?>"><meta property="og:url" content="<?=daily_share_e($canonical)?>"><meta property="og:image" content="https://beyondimagination.co.technology<?=daily_share_e($imagePath)?>"><link rel="stylesheet" href="assets/css/web-app.css?v=2.3.0"><style>
*{box-sizing:border-box}body{margin:0;min-height:100vh;padding:24px 14px 90px;color:#fffdf9;background:radial-gradient(circle at top,#17472d,#061b12 62%);font:16px/1.6 system-ui,sans-serif}.shell{width:min(1040px,100%);margin:auto}.top{display:flex;align-items:center;justify-content:space-between;gap:12px;margin:0 0 22px}.top a{color:#f3d895;font-weight:750}.top h1{margin:0;font:500 26px Georgia,serif}.scripture-card{display:flex;min-height:480px;flex-direction:column;align-items:center;justify-content:center;gap:22px;padding:100px 10%;border:1px solid #cfa759;border-radius:22px;background:<?=daily_share_e($cardBackground)?>;text-align:center;box-shadow:0 24px 70px #00120988}.eyebrow{color:#f4d898;font:600 15px Georgia,serif;text-shadow:0 2px 12px #00170f}.passage{max-width:30ch;margin:0;color:#fffdf9;font:500 clamp(28px,5vw,54px)/1.2 Georgia,'Noto Naskh Arabic','Geeza Pro',serif;white-space:pre-wrap;text-shadow:0 3px 22px #00150ee6}.reference{color:#f6d891;font:600 clamp(22px,3vw,32px)/1.25 Georgia,serif;text-shadow:0 2px 14px #00150e}.reflection{max-width:56ch;margin:0;color:#fff5dc}.brand{color:#f4d898;font-weight:800;letter-spacing:.05em}.actions{display:flex;justify-content:center;flex-wrap:wrap;gap:10px;margin:16px 0 26px}.actions button,.actions a{min-height:46px;padding:11px 16px;border:1px solid #e9cc83;border-radius:999px;color:#092117;background:#efd692;font:800 14px system-ui;text-decoration:none;cursor:pointer}.reading{padding:20px;border:1px solid #ffffff2d;border-radius:17px;background:#0d3022e8}.reading a{color:#f4d898}.reading h2{margin:0 0 8px;font:500 23px Georgia,serif}.reading p{white-space:pre-wrap} [dir=rtl] .passage,[dir=rtl] .reflection{text-align:center;unicode-bidi:plaintext}@media(max-width:600px){body{padding:12px 10px 86px}.top h1{font-size:21px}.scripture-card{min-height:580px;padding:150px 9% 135px;border-radius:16px;background-image:<?=daily_share_e($mobileBackground)?>}.passage{font-size:clamp(28px,8vw,40px)}.reading{padding:16px}}
</style></head><body><main class="shell"><header class="top"><h1>Daily Breath</h1><a href="index.php?faith=<?=daily_share_e($tradition)?>">Open the app →</a></header><article class="scripture-card" id="share-card" data-image="<?=daily_share_e($useArtwork ? $imagePath : '') ?>" data-tradition="<?=daily_share_e($tradition)?>"><span class="eyebrow"><?=daily_share_e($faithLabel.' '.$kind.' of the Day · '.dailybreath_web_date($date))?></span><blockquote class="passage" id="share-passage"><?=daily_share_e($content['passage'])?></blockquote><strong class="reference" id="share-reference"><?=daily_share_e($content['reference'])?></strong><?php if(trim((string)$content['reflection'])!==''):?><p class="reflection" id="share-reflection"><?=daily_share_e($content['reflection'])?></p><?php endif?><span class="brand">@thedaybreath · Faith · Recovery · Hope</span></article><nav class="actions" aria-label="Share this daily reading"><button type="button" id="download-card">Download image</button><button type="button" id="share-reading">Share</button><button type="button" id="listen-reading">Listen</button><a href="<?=daily_share_e($readerUrl)?>">Read in context →</a></nav><section class="reading"><h2><?=daily_share_e($faithLabel)?> · <?=daily_share_e($content['reference'])?></h2><p><?=daily_share_e($content['passage'])?></p><?php if(trim((string)$content['reflection'])!==''):?><h2>Reflection</h2><p><?=daily_share_e($content['reflection'])?></p><?php endif?><p class="brand">Daily Breath · <?=daily_share_e(dailybreath_web_date($date))?></p></section></main><script src="assets/js/share-card.js?v=2.3.0" defer></script></body></html>
