<?php
declare(strict_types=1);
require_once __DIR__ . '/../includes/ecosystem.php';
require_once __DIR__ . '/includes/web-app.php';
$wallet=beyond_app_bootstrap('DailyBreath');$pdo=beyond_db();$userId=(int)$_SESSION['user_id'];
$days=[];for($i=0;$i<35;$i++){$date=date('Y-m-d',strtotime("-$i days"));$days[$date]=['breathing'=>0,'reflections'=>0];}
try{$s=$pdo->prepare('SELECT DATE(completed_at) activity_date,COUNT(*) total FROM breathing_sessions WHERE user_id=? AND completed_at>=? GROUP BY DATE(completed_at)');$s->execute([$userId,array_key_last($days)]);foreach($s as $r)if(isset($days[$r['activity_date']]))$days[$r['activity_date']]['breathing']=(int)$r['total'];}catch(Throwable $e){}
try{$s=$pdo->prepare('SELECT entry_date activity_date,COUNT(*) total FROM reflection_journal_entries WHERE user_id=? AND entry_date>=? GROUP BY entry_date');$s->execute([$userId,array_key_last($days)]);foreach($s as $r)if(isset($days[$r['activity_date']]))$days[$r['activity_date']]['reflections']=(int)$r['total'];}catch(Throwable $e){}
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Daily History | DailyBreath</title><?=dailybreath_web_head('Daily History | DailyBreath')?><style>*{box-sizing:border-box}body{margin:0;min-height:100vh;color:#f4f8f4;background:linear-gradient(#06170ec4,#06170ff2),url('../assets/dailybreath-login-background.webp') center/cover fixed;font:15px Inter,system-ui}.shell{width:min(900px,calc(100% - 32px));margin:auto;padding:44px 0 110px}.top{display:flex;justify-content:space-between}.top a{color:#f0cb77}.hero{margin:42px 0 25px}.hero h1{margin:8px 0;font:clamp(42px,7vw,64px) Georgia,serif}.hero p{color:#bbcabf;line-height:1.6}.calendar{display:grid;grid-template-columns:repeat(7,1fr);gap:9px}.day{min-height:105px;padding:12px;border:1px solid #ffffff25;border-radius:16px;background:#123b2ab8}.day.today{border-color:#f0cb77;box-shadow:0 0 0 2px #f0cb7730}.date{display:block;color:#c6d4c9;font-size:12px}.date strong{display:block;color:#fff;font-size:20px;margin-top:3px}.marks{display:flex;gap:6px;flex-wrap:wrap;margin-top:12px}.mark{padding:5px 7px;border-radius:999px;background:#ffffff12;color:#dbe8dd;font-size:10px}.empty{color:#8fa095}.note{margin-top:20px;padding:17px;border-radius:16px;background:#ffffff0d;color:#c4d2c7;line-height:1.6}@media(max-width:620px){.calendar{grid-template-columns:repeat(2,1fr)}.day{min-height:90px}}</style></head><body><main class="shell"><header class="top"><strong>DailyBreath · History</strong><a href="settings.php">Settings →</a></header><section class="hero"><small>THE LAST FIVE WEEKS</small><h1>Your gentle rhythm.</h1><p>This is a record, not a score. Notice what has supported you and return whenever you’re ready.</p></section><section class="calendar" aria-label="Daily activity history"><?php foreach($days as $date=>$activity):?><article class="day <?=$date===date('Y-m-d')?'today':''?>"><time class="date" datetime="<?=e($date)?>"><?=e(date('D',strtotime($date)))?><strong><?=e(date('M j',strtotime($date)))?></strong></time><div class="marks"><?php if($activity['breathing']):?><span class="mark">Breathe ×<?=$activity['breathing']?></span><?php endif;?><?php if($activity['reflections']):?><span class="mark">Reflect ×<?=$activity['reflections']?></span><?php endif;?><?php if(!$activity['breathing']&&!$activity['reflections']):?><span class="empty">Quiet day</span><?php endif;?></div></article><?php endforeach;?></section><p class="note">Verse and devotional availability is automatic every day. This calendar only marks activities you intentionally save.</p></main><?=dailybreath_web_scripts()?><script src="/assets/js/visitor-analytics.js" defer></script></body></html>

