<?php
declare(strict_types=1);
require_once __DIR__ . '/../includes/ecosystem.php';
require_once __DIR__ . '/includes/web-app.php';
$wallet = beyond_app_bootstrap('DailyBreath');
$email = (string)($_SESSION['email'] ?? '');
$name = trim((string)($_SESSION['name'] ?? ''));
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Settings & About | DailyBreath</title><?= dailybreath_web_head('Settings & About | DailyBreath') ?><style>
*{box-sizing:border-box}body{margin:0;min-height:100vh;color:#eef6ef;background:linear-gradient(#07190fb8,#07190ff0) center/cover fixed;font:15px/1.55 Inter,system-ui}.shell{width:min(820px,calc(100% - 32px));margin:auto;padding:44px 0 100px}.top{display:flex;justify-content:space-between;align-items:center}.top a,.link{color:#f0cb77}.hero{margin:44px 0 24px}.hero h1{margin:5px 0;font:clamp(42px,7vw,64px) Georgia,serif}.muted{color:#b9c9bd}.card{margin:14px 0;padding:24px;border:1px solid #ffffff2e;border-radius:22px;background:#123b2ac9;box-shadow:0 18px 50px #0005}.card h2{margin-top:0}.row{display:flex;align-items:center;justify-content:space-between;gap:20px;padding:13px 0;border-bottom:1px solid #ffffff18}.row:last-child{border:0}.row label{font-weight:800}.row small{display:block;color:#b9c9bd;font-weight:400}.row select,.row input{min-width:170px;padding:10px 12px;border:1px solid #ffffff2d;border-radius:12px;color:#fff;background:#0a291d;font:inherit}.newsletter{display:grid;grid-template-columns:1fr 1fr auto;gap:10px}.newsletter input{min-width:0;width:100%;padding:12px;border:1px solid #ffffff2d;border-radius:12px;color:#fff;background:#0a291d}.btn{padding:12px 16px;border:0;border-radius:12px;color:#173f2c;background:#f0cb77;font-weight:900;cursor:pointer}.version{display:flex;justify-content:space-between;color:#b9c9bd}@media(max-width:650px){.row{align-items:flex-start;flex-direction:column}.row select,.row input{width:100%}.newsletter{grid-template-columns:1fr}}
</style><style>
body{color:var(--db-ink);background:radial-gradient(circle at 8% 4%,#f1e9ff 0,transparent 27%),linear-gradient(150deg,#fffcf8,#f4f0fb 55%,#f8eef2)}.top a,.link{color:var(--db-accent)}.muted,.row small,.version{color:#706983}.card{border-color:var(--db-line);background:#fffdfbe8;box-shadow:0 18px 50px #30264b12}.row{border-color:var(--db-line)}.row select,.row input,.newsletter input{border-color:var(--db-line);background:#fff;color:var(--db-ink)}.btn{color:#fff;background:var(--db-accent)}html[data-db-theme=dusk] body{color:#f7f4ff;background:radial-gradient(circle at 8% 4%,#39315c 0,transparent 28%),linear-gradient(150deg,#151223,#211b35 55%,#181426)}html[data-db-theme=dusk] .card{background:#242039dc;border-color:#4b4466}html[data-db-theme=dusk] .muted,html[data-db-theme=dusk] .row small,html[data-db-theme=dusk] .version{color:#c5bed8}html[data-db-theme=dusk] .row{border-color:#4b4466}html[data-db-theme=dusk] .row select,html[data-db-theme=dusk] .row input,html[data-db-theme=dusk] .newsletter input{background:#19162a;border-color:#4b4466;color:#fff}
</style></head><body><main class="shell"><header class="top"><strong>DailyBreath · Settings</strong><a href="index.php">Home →</a></header><section class="hero"><small>YOUR EXPERIENCE</small><h1>Settings & About</h1><p class="muted">Preferences stay on this device. Your signed-in journal and challenge progress stay with your Beyond ID.</p></section>
<section class="card"><h2>Appearance</h2><div class="row"><label for="theme">Theme<small>Use your device setting or choose a DailyBreath palette.</small></label><select id="theme"><option value="system">System</option><option value="dawn">Dawn</option><option value="dusk">Dusk</option><option value="lilac">Lilac</option></select></div><div class="row"><label for="motion">Reduce motion<small>Limits decorative motion where possible.</small></label><input id="motion" type="checkbox"></div></section>
<section class="card"><h2>Faith tradition</h2><p class="muted">Choose which daily reading and complete local library opens on DailyBreath.</p><div class="row"><span>Bible</span><a class="link" href="index.php?faith=bible">Choose →</a></div><div class="row"><span>Tanakh</span><a class="link" href="index.php?faith=torah">Choose →</a></div><div class="row"><span>Quran</span><a class="link" href="index.php?faith=quran">Choose →</a></div></section>
<section class="card"><h2>Recovery newsletter</h2><p class="muted">Optional encouragement and recovery-support updates. You can unsubscribe at any time.</p><form class="newsletter" action="subscribe.php" method="post"><input type="hidden" name="_csrf" value="<?= e(beyond_csrf_token()) ?>"><input name="website" tabindex="-1" autocomplete="off" style="position:absolute;left:-9999px" aria-hidden="true"><input name="name" value="<?= e($name) ?>" placeholder="Name"><input type="email" name="email" value="<?= e($email) ?>" placeholder="Email address" required><button class="btn">Subscribe</button></form></section>
<section class="card"><h2>Privacy, support & attribution</h2><div class="row"><span>Daily history</span><a class="link" href="history.php">View activity →</a></div><div class="row"><span>Recovery support</span><a class="link" href="support.php">Open support page →</a></div><div class="row"><span>Privacy</span><a class="link" href="../legal/privacy.php">Read privacy policy →</a></div><div class="row"><span>Support</span><a class="link" href="mailto:support@beyond-os.com?subject=DailyBreath%20support">Email support →</a></div><div class="row"><span>Bible and Torah text<small>World English Bible (WEBP), public domain.</small></span><a class="link" href="https://ebible.org/details.php?id=engwebp" rel="noopener">Attribution →</a></div><div class="row"><span>Quran English meaning<small>Marmaduke Pickthall translation, Project Gutenberg eBook 16955.</small></span><a class="link" href="https://www.gutenberg.org/ebooks/16955" rel="noopener">Attribution →</a></div></section>
<p class="version"><span>DailyBreath web</span><strong><?= e(DAILYBREATH_WEB_VERSION) ?></strong></p></main>
<script>addEventListener('DOMContentLoaded',()=>{const s=DailyBreath.settings,t=document.getElementById('theme'),m=document.getElementById('motion');t.value=s.theme;m.checked=!!s.reduceMotion;const save=()=>{DailyBreath.save({theme:t.value,reduceMotion:m.checked});DailyBreath.toast('Settings saved.');setTimeout(()=>location.reload(),300)};t.onchange=save;m.onchange=save})</script><?= dailybreath_web_scripts() ?><script src="/assets/js/visitor-analytics.js" defer></script></body></html>
