<?php
declare(strict_types=1);
require_once __DIR__ . '/../config/bootstrap.php';
require_once __DIR__ . '/includes/web-app.php';
require_once __DIR__ . '/includes/sacred-text.php';
$tradition = dailybreath_faith_tradition((string)($_GET['faith'] ?? 'bible'));
$questions = [
    ['A calm, steady breath can help you…', ['Create a brief pause', 'Avoid all feelings', 'Solve everything at once', 'Skip rest'], 0],
    ['A helpful reflection practice begins by…', ['Noticing what is present', 'Comparing yourself to others', 'Ignoring your experience', 'Demanding a perfect answer'], 0],
    ['Reading a sacred text thoughtfully can include…', ['Pausing to consider its meaning', 'Rushing to finish first', 'Never asking questions', 'Reading without attention'], 0],
    ['When you need support, a healthy choice may be to…', ['Reach out to someone you trust', 'Carry everything alone', 'Hide your needs', 'Give up on your routine'], 0],
    ['Gratitude can help us…', ['Notice what is good and sustaining', 'Pretend challenges are not real', 'Compete with friends', 'Make life perfect'], 0],
];
$score = null;
if ($_SERVER['REQUEST_METHOD'] === 'POST' && verify_csrf_token($_POST['csrf'] ?? null)) { $score=0; foreach ($questions as $i=>$question) if ((int)($_POST['q'][$i] ?? -1) === $question[2]) $score++; }
?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Trivia | DailyBreath</title><?= dailybreath_web_head('DailyBreath Trivia') ?><style>body{margin:0;min-height:100vh;background:#eef5ef;color:#173f2c;font-family:Inter,system-ui,sans-serif}.shell{width:min(760px,calc(100% - 32px));margin:auto;padding:44px 0 90px}.back{color:#286543;font-weight:800}.card{margin-top:20px;padding:clamp(24px,5vw,44px);background:#fff;border:1px solid #d4e3d5;border-radius:26px;box-shadow:0 20px 50px #173f2c12}.eyebrow{color:#4e9066;font-size:12px;font-weight:900;letter-spacing:.14em}.card h1{font:800 clamp(34px,6vw,52px)/1.05 Georgia,serif;margin:13px 0}.intro{color:#5f7565;line-height:1.6}.question{padding:22px 0;border-bottom:1px solid #e1ebe2}.question h2{font-size:18px}.option{display:block;margin:9px 0;padding:13px;border:1px solid #d8e5da;border-radius:13px;background:#f7fbf7;cursor:pointer}.option:has(input:checked){border-color:#4e9066;background:#eaf6ec}.option input{accent-color:#286543;margin-right:8px}.btn{margin-top:25px;padding:13px 20px;border:0;border-radius:13px;background:#286543;color:#fff;font-weight:900;cursor:pointer}.result{margin:20px 0;padding:16px;border-radius:14px;background:#eaf6ec;color:#245a3a;font-weight:800}</style></head><body><main class="shell"><a class="back" href="index.php?faith=<?= e($tradition) ?>">← DailyBreath home</a><section class="card"><div class="eyebrow">DAILYBREATH TRIVIA · <?= e(dailybreath_tradition_label($tradition)) ?></div><h1>Pause, reflect, learn.</h1><p class="intro">Five gentle questions about steady practices, reflection, and care. This is a moment for learning, not a test of faith.</p><?php if ($score !== null): ?><div class="result">You chose <?= $score ?> of <?= count($questions) ?> caring answers. Keep one helpful idea with you today.</div><?php endif; ?><form method="post"><input type="hidden" name="csrf" value="<?= e(csrf_token()) ?>"><?php foreach ($questions as $i=>$question): ?><fieldset class="question"><h2><?= $i+1 ?>. <?= e($question[0]) ?></h2><?php foreach ($question[1] as $j=>$option): ?><label class="option"><input required type="radio" name="q[<?= $i ?>]" value="<?= $j ?>"> <?= e($option) ?></label><?php endforeach; ?></fieldset><?php endforeach; ?><button class="btn">Reflect on my answers</button></form></section></main><?= dailybreath_web_scripts() ?></body></html>
