<?php
declare(strict_types=1);
require_once __DIR__.'/../../includes/platform.php';
require_once __DIR__.'/../includes/crypto-watch.php';
require_once __DIR__.'/../includes/beyond-cash.php';
$wallet=beyond_app_bootstrap('Beyond Wallet');
global $pdo;
$cashAccounts=beyond_cash_accounts($pdo,(int)$_SESSION['user_id']);
$cryptoMessage='';$cryptoError='';$cryptoAccounts=[];$cryptoNetworks=beyond_crypto_networks();
if($_SERVER['REQUEST_METHOD']==='POST'&&isset($_POST['crypto_action'])){
    if(!bos_verify_csrf($_POST['csrf']??null))$cryptoError='Your session expired. Refresh and try again.';
    else{
        try{
            $action=(string)$_POST['crypto_action'];
            if($action==='add'){
                $network=strtoupper(trim((string)($_POST['network']??'')));$address=trim((string)($_POST['public_address']??''));$label=trim((string)($_POST['label']??''));
                if(!isset($cryptoNetworks[$network]))throw new InvalidArgumentException('Choose a supported network.');
                if(!beyond_crypto_valid_address($network,$address))throw new InvalidArgumentException('Enter a valid public '.$network.' address.');
                $label=substr($label!==''?$label:$cryptoNetworks[$network]['name'].' wallet',0,80);
                $statement=$pdo->prepare('INSERT INTO crypto_watch_accounts(user_id,network,label,public_address,address_hash) VALUES(?,?,?,?,?)');
                $statement->execute([(int)$_SESSION['user_id'],$network,$label,$address,hash('sha256',strtolower($address))]);
                $cryptoMessage='Watch-only wallet added.';
            }elseif($action==='remove'){
                $statement=$pdo->prepare('DELETE FROM crypto_watch_accounts WHERE id=? AND user_id=?');
                $statement->execute([(int)($_POST['account_id']??0),(int)$_SESSION['user_id']]);
                $cryptoMessage='Watch-only wallet removed.';
            }
        }catch(Throwable $exception){$cryptoError=$exception instanceof PDOException?'That public address is already connected.':$exception->getMessage();}
    }
}
$cryptoStatement=$pdo->prepare('SELECT id,network,label,public_address,created_at FROM crypto_watch_accounts WHERE user_id=? ORDER BY created_at DESC');
$cryptoStatement->execute([(int)$_SESSION['user_id']]);$cryptoAccounts=$cryptoStatement->fetchAll(PDO::FETCH_ASSOC);
$transactions=[];
try{$stmt=$pdo->prepare('SELECT t.* FROM beyond_wallet_transactions t JOIN beyond_wallets w ON w.id=t.wallet_id WHERE w.user_id=? ORDER BY t.created_at DESC LIMIT 50');$stmt->execute([(int)$_SESSION['user_id']]);$transactions=$stmt->fetchAll(PDO::FETCH_ASSOC);}catch(Throwable $e){}
$earned=0.0;$spent=0.0;
foreach($transactions as $item){$amount=(float)($item['amount']??0);if(($item['type']??'')==='credit')$earned+=abs($amount);else $spent+=abs($amount);}
$balance=(float)($wallet['balance']??0);
$bitsPerUsd=100.0;
$usdEstimate=$balance/$bitsPerUsd;
?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#171025"><title>Beyond Wallet | Beyond OS 2.3.3</title><link rel="stylesheet" href="../assets/css/admin-v2.css?v=2.3.3"><style>
.wallet-page{max-width:1180px;margin:auto}.wallet-hero{position:relative;overflow:hidden;display:grid;grid-template-columns:minmax(0,1.2fr) minmax(260px,.8fr);gap:28px;align-items:end;padding:clamp(28px,5vw,54px);background:radial-gradient(circle at 86% 12%,#fd5e9b55,transparent 32%),linear-gradient(135deg,#28205d,#762678 58%,#bd326f);color:#fff}.wallet-hero:after{position:absolute;right:-80px;bottom:-120px;width:330px;height:330px;border:1px solid #ffffff22;border-radius:50%;content:""}.wallet-balance h1{font-size:clamp(52px,8vw,86px);margin:12px 0 7px;letter-spacing:-.065em;line-height:.9}.wallet-balance p{max-width:560px;margin:18px 0 0;color:#f1deee}.balance-mark{font-size:clamp(62px,8vw,102px);font-weight:950;text-align:right;opacity:.28;letter-spacing:-.08em}.metric-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:14px;margin-top:16px}.metric{padding:20px;border:1px solid var(--border);border-radius:18px;background:var(--panel);box-shadow:var(--shadow-soft)}.metric small{display:block;color:var(--muted);font-weight:800;text-transform:uppercase;letter-spacing:.09em}.metric strong{display:block;margin-top:9px;font-size:clamp(21px,3vw,30px)}
.value-card{margin-top:16px}.value-heading{display:flex;align-items:flex-start;justify-content:space-between;gap:18px}.value-heading p{max-width:620px;margin:8px 0 0;color:var(--muted)}.rate-pill{padding:8px 12px;border:1px solid var(--border);border-radius:999px;background:var(--panel2);color:var(--muted);font-size:12px;font-weight:800;white-space:nowrap}.value-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:14px;margin-top:22px}.value-tile{position:relative;overflow:hidden;padding:22px;border:1px solid var(--border);border-radius:18px;background:var(--panel2)}.value-tile:after{position:absolute;right:-28px;bottom:-42px;width:120px;height:120px;border-radius:50%;background:var(--accent-soft);content:""}.value-tile span,.value-tile strong,.value-tile small{position:relative;z-index:1;display:block}.value-tile span{color:var(--muted);font-size:12px;font-weight:800;text-transform:uppercase;letter-spacing:.08em}.value-tile strong{margin-top:10px;font-size:clamp(28px,4vw,42px);line-height:1;letter-spacing:-.045em}.value-tile small{margin-top:9px;color:var(--muted)}.conversion-tool{display:grid;grid-template-columns:minmax(0,1fr) auto minmax(0,1fr);gap:14px;align-items:end;margin-top:18px;padding:18px;border:1px solid var(--border);border-radius:18px;background:var(--panel2)}.conversion-tool label{display:grid;gap:7px;color:var(--muted);font-size:12px;font-weight:800}.conversion-result{display:grid;grid-template-columns:1fr 1fr;gap:10px}.conversion-result div{padding:12px 14px;border:1px solid var(--border);border-radius:14px;background:var(--panel)}.conversion-result span,.conversion-result strong{display:block}.conversion-result span{color:var(--muted);font-size:11px}.conversion-result strong{margin-top:3px;font-size:18px}.conversion-arrow{padding-bottom:13px;color:var(--accent);font-size:24px;font-weight:900}.disclaimer{margin:16px 0 0;padding:14px;border-radius:14px;background:var(--accent-soft);color:var(--muted);font-size:12px;line-height:1.5}.activity-card{margin-top:16px}.receipt{display:flex;justify-content:space-between;gap:12px;padding:15px 0;border-bottom:1px solid var(--border)}.receipt:last-child{border-bottom:0}.empty-actions{display:flex;gap:10px;flex-wrap:wrap;margin-top:18px}
.crypto-card{margin-top:16px}.crypto-form{display:grid;grid-template-columns:150px minmax(130px,.5fr) minmax(260px,1.5fr) auto;gap:10px;align-items:end;margin-top:18px}.crypto-form label{display:grid;gap:7px;color:var(--muted);font-size:12px;font-weight:800}.crypto-form input,.crypto-form select{width:100%;padding:13px;border:1px solid var(--border);border-radius:12px;background:var(--panel2);color:var(--text)}.crypto-list{display:grid;gap:12px;margin-top:20px}.crypto-account{display:grid;grid-template-columns:auto minmax(0,1fr) auto auto;gap:14px;align-items:center;padding:17px;border:1px solid var(--border);border-radius:16px;background:var(--panel2)}.crypto-symbol{display:grid;width:45px;height:45px;place-items:center;border-radius:50%;background:var(--accent-soft);font-weight:950}.crypto-address{display:block;overflow:hidden;color:var(--muted);font:12px ui-monospace,monospace;text-overflow:ellipsis;white-space:nowrap}.crypto-live{min-width:130px;text-align:right}.crypto-live strong,.crypto-live small{display:block}.crypto-live small{color:var(--muted)}.crypto-remove{padding:9px;border:0;background:transparent;color:var(--muted);cursor:pointer}.message{margin-top:12px;padding:11px 14px;border-radius:12px;background:rgba(70,200,120,.12)}.message.error{background:rgba(255,80,100,.12)}
.cash-card{margin-top:16px}.cash-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px;margin-top:20px}.cash-account{padding:24px;border:1px solid var(--border);border-radius:20px;background:linear-gradient(145deg,var(--panel2),var(--panel))}.cash-account header{display:flex;justify-content:space-between;gap:12px}.cash-account header span{font-weight:900}.cash-account header small{color:var(--muted)}.cash-account strong{display:block;margin-top:18px;font-size:clamp(36px,5vw,54px);letter-spacing:-.05em}.cash-account p{margin:8px 0 0;color:var(--muted)}.ledger-note{display:grid;grid-template-columns:auto 1fr;gap:12px;margin-top:16px;padding:16px;border:1px solid var(--border);border-radius:16px}.ledger-note b{color:var(--accent)}
@media(max-width:850px){.wallet-hero{grid-template-columns:1fr}.balance-mark{text-align:left}.metric-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.value-grid{grid-template-columns:1fr}.conversion-tool,.crypto-form{grid-template-columns:1fr}.conversion-arrow{display:none}.crypto-account{grid-template-columns:auto minmax(0,1fr) auto}.crypto-live{grid-column:2;text-align:left}}@media(max-width:560px){.content{padding:16px}.wallet-hero{padding:25px 20px}.metric-grid,.cash-grid{grid-template-columns:1fr}.metric{padding:16px}.receipt{align-items:flex-start;flex-direction:column}.value-heading{flex-direction:column}.conversion-result{grid-template-columns:1fr}}
</style></head><body><main class="content wallet-page">
<section class="card wallet-hero"><div class="wallet-balance"><span class="badge">BEYOND BITS</span><h1><?=number_format($balance,0)?> <?=e((string)($wallet['currency']??'BITS'))?></h1><p>Your reward balance follows your Beyond ID across every connected app. Earn 10 bit$ for each completed lesson and 50 bit$ for each completed module.</p></div><div class="balance-mark">bit$</div></section>
<section class="metric-grid" aria-label="Wallet summary"><article class="metric"><small>Available</small><strong><?=number_format($balance,0)?> bit$</strong></article><article class="metric"><small>Lifetime earned</small><strong><?=number_format($earned,0)?> bit$</strong></article><article class="metric"><small>Lifetime spent</small><strong><?=number_format($spent,0)?> bit$</strong></article><article class="metric"><small>Transactions</small><strong><?=count($transactions)?></strong></article></section>
<section class="card value-card"><div class="value-heading"><div><span class="badge">VALUE COMPARISON</span><h2>Your bit$ in USD and CAD</h2><p>See the estimated purchasing value of your Beyond balance in both currencies.</p></div><span class="rate-pill">100 bit$ = US$1.00</span></div><div class="value-grid" aria-label="bit$ value comparison"><article class="value-tile"><span>Beyond balance</span><strong><?=number_format($balance,0)?> bit$</strong><small>Your available rewards</small></article><article class="value-tile"><span>USD estimate</span><strong><?=number_format($usdEstimate,2)?> USD</strong><small>At the Beyond reference rate</small></article><article class="value-tile"><span>CAD estimate</span><strong id="balanceCad">Loading…</strong><small id="cadRate">Checking today’s USD/CAD rate</small></article></div><div class="conversion-tool"><label for="bitsToCompare">Compare another bit$ amount<input id="bitsToCompare" type="number" min="0" step="1" inputmode="numeric" value="<?=e((string)(int)$balance)?>"></label><span class="conversion-arrow" aria-hidden="true">→</span><div class="conversion-result" aria-live="polite"><div><span>USD</span><strong id="compareUsd">—</strong></div><div><span>CAD</span><strong id="compareCad">—</strong></div></div></div><p class="disclaimer">This is a reference comparison for purchases inside Beyond OS. bit$ are closed-loop ecosystem rewards—not cryptocurrency, legal tender, or a cash balance—and have no guaranteed cash-out value.</p></section>
<section class="card cash-card"><div class="value-heading"><div><span class="badge">BEYOND CASH</span><h2>Provider-backed money</h2><p>CAD and USD funds will live here after DCBank onboarding. This balance is entirely separate from bit$ Rewards.</p></div><span class="rate-pill">DCBank connection pending</span></div><div class="cash-grid"><?php foreach(['CAD','USD'] as $currency):$account=$cashAccounts[$currency]??[];?><article class="cash-account"><header><span><?=e($currency)?> balance</span><small><?=($account['status']??'pending_provider')==='active'?'Available':'Not activated'?></small></header><strong><?=number_format((float)($account['available_balance']??0),2)?> <?=e($currency)?></strong><p><?=number_format((float)($account['pending_balance']??0),2)?> pending</p></article><?php endforeach;?></div><div class="ledger-note"><b>Two-ledger protection</b><span>Only reconciled provider funds may enter Beyond Cash. Learning rewards remain in bit$ and can never increase a cash balance.</span></div></section>
<section class="card crypto-card"><div class="value-heading"><div><span class="badge">CRYPTO PORTFOLIO</span><h2>Watch your on-chain balances</h2><p>Connect public wallet addresses to view BTC, ETH, and SOL. After provider activation, completed crypto conversions will settle into Beyond Cash—not bit$ Rewards.</p></div><span class="rate-pill">Watch-only</span></div><?php if($cryptoMessage):?><p class="message"><?=e($cryptoMessage)?></p><?php endif;?><?php if($cryptoError):?><p class="message error"><?=e($cryptoError)?></p><?php endif;?><form class="crypto-form" method="post"><input type="hidden" name="csrf" value="<?=e(bos_csrf_token())?>"><input type="hidden" name="crypto_action" value="add"><label>Network<select name="network"><?php foreach($cryptoNetworks as $code=>$details):?><option value="<?=e($code)?>"><?=e($details['name'])?> (<?=e($code)?>)</option><?php endforeach;?></select></label><label>Wallet label<input name="label" maxlength="80" placeholder="My wallet"></label><label>Public address<input name="public_address" maxlength="128" autocomplete="off" spellcheck="false" required placeholder="Paste a public address only"></label><button class="btn" type="submit">Add wallet</button></form><p class="disclaimer"><strong>Never enter a seed phrase or private key.</strong> Beyond Wallet stores public addresses only. It cannot move, recover, or protect cryptocurrency. Balance requests reveal the public address to the configured blockchain data provider.</p><div class="crypto-list"><?php if(!$cryptoAccounts):?><p class="muted">No crypto wallets connected yet.</p><?php endif;?><?php foreach($cryptoAccounts as $account):?><article class="crypto-account" data-crypto-account="<?=intval($account['id'])?>" data-network="<?=e($account['network'])?>"><span class="crypto-symbol"><?=e($account['network'])?></span><div><strong><?=e($account['label'])?></strong><span class="crypto-address" title="<?=e($account['public_address'])?>"><?=e($account['public_address'])?></span></div><div class="crypto-live" aria-live="polite"><strong>Loading…</strong><small>Live balance</small></div><form method="post"><input type="hidden" name="csrf" value="<?=e(bos_csrf_token())?>"><input type="hidden" name="crypto_action" value="remove"><input type="hidden" name="account_id" value="<?=intval($account['id'])?>"><button class="crypto-remove" type="submit" aria-label="Remove <?=e($account['label'])?>">Remove</button></form></article><?php endforeach;?></div></section>
<section class="card activity-card"><div class="card-heading"><h2>Wallet activity</h2><span class="badge"><?=count($transactions)?> entries</span></div><?php if(!$transactions):?><p class="muted">No wallet activity yet. Complete your profile to earn your first 100 bit$.</p><div class="empty-actions"><a class="btn" href="profile.php">Complete profile</a><a class="btn btn-secondary" href="/app-store/">Explore earning apps</a></div><?php endif;?><?php foreach($transactions as $item):?><div class="receipt"><span><?=e((string)($item['description']?:$item['app_slug']))?><br><small class="muted"><?=e((string)$item['created_at'])?></small></span><strong><?=$item['type']==='credit'?'+':'−'?><?=number_format(abs((float)$item['amount']),0)?> bit$</strong></div><?php endforeach;?></section>
</main><script>
(()=>{const bits=document.getElementById('bitsToCompare'),usd=document.getElementById('compareUsd'),cad=document.getElementById('compareCad'),balanceCad=document.getElementById('balanceCad'),cadRate=document.getElementById('cadRate');const balance=<?=json_encode($balance)?>,bitsPerUsd=<?=json_encode($bitsPerUsd)?>;let usdCad=1.37;const money=(n,c)=>new Intl.NumberFormat('en-CA',{style:'currency',currency:c,minimumFractionDigits:2,maximumFractionDigits:2}).format(n);function render(){const amount=Math.max(0,Number(bits.value)||0),usdValue=amount/bitsPerUsd;usd.textContent=money(usdValue,'USD');cad.textContent=money(usdValue*usdCad,'CAD');balanceCad.textContent=money((balance/bitsPerUsd)*usdCad,'CAD')}async function loadRate(){try{const response=await fetch('https://open.er-api.com/v6/latest/USD',{cache:'no-store'});if(!response.ok)throw Error('Exchange rate unavailable');const data=await response.json(),rate=Number(data.rates&&data.rates.CAD);if(!Number.isFinite(rate)||rate<=0)throw Error('Invalid exchange rate');usdCad=rate;cadRate.textContent='Using today’s USD/CAD market rate'}catch(error){cadRate.textContent='Using an indicative USD/CAD rate'}render()}bits.addEventListener('input',render);render();loadRate()})();
document.querySelectorAll('[data-crypto-account]').forEach(async card=>{const output=card.querySelector('.crypto-live strong'),network=card.dataset.network;try{const response=await fetch(`crypto-balance.php?id=${encodeURIComponent(card.dataset.cryptoAccount)}`,{cache:'no-store'}),data=await response.json();if(!response.ok||!data.ok)throw Error(data.error||'Unavailable');output.textContent=new Intl.NumberFormat('en-US',{maximumFractionDigits:8}).format(data.balance)+' '+network}catch(error){output.textContent='Unavailable'}});
</script><script src="/assets/js/visitor-analytics.js" defer></script></body></html>
