INSERT INTO tattoo_studios
  (slug,name,description,address_line1,city,province,postal_code,country,phone,owner_display_name,owner_instagram_url,instagram_url,services,walk_ins,status,source_note)
VALUES
  ('obscura-tattoo-ottawa','Obscura Tattoo','Downtown Ottawa studio offering custom tattoo work in a private, appointment-focused setting.','320 Catherine Street, Suite 22','Ottawa','Ontario','K1R 5T5','Canada','613-218-3116','Studio team','https://www.obscuratattoo.ca/','https://www.obscuratattoo.ca/','Custom tattooing, blackwork, illustrative, fine line',0,'active','Verified from the official studio website on 2026-08-22'),
  ('the-18th-ink-ottawa','The 18th Ink','Ottawa studio with artists covering colour realism, black-and-grey, Japanese and anime work.','250 Greenbank Road, Unit 14','Ottawa','Ontario','K2H 8X4','Canada','613-240-7465','Studio team','https://www.the18thinked.com/','https://www.the18thinked.com/','Colour realism, black-and-grey, Japanese, anime',0,'active','Verified from the official studio website on 2026-08-22'),
  ('sting-studio-ottawa','Sting Studio','Private east-end Ottawa shop specializing in custom tattoos, blackwork, bold colour and piercing.','1076 Ogilvie Road, Unit 2','Ottawa','Ontario','','Canada','249-294-0612','Derrick','https://www.stingstudio.ca/','https://www.stingstudio.ca/','Custom tattoos, blackwork, neo-traditional, colour, piercing',0,'active','Verified from the official studio website on 2026-08-22'),
  ('sunken-star-tattoo-ottawa','Sunken Star Tattoo','ByWard Market studio focused on meaningful custom designs, careful consultations and professional tattooing.','288 Dalhousie Street, Unit 100','Ottawa','Ontario','K1N 7E6','Canada','613-948-8997','Studio team','https://www.sunkenstartattoo.com/','https://www.sunkenstartattoo.com/','Custom tattooing, consultation, black-and-grey, colour',1,'active','Verified from the official studio website on 2026-08-22'),
  ('two-0-six-tattoo-ottawa','Two 0 Six Tattoo','Hintonburg studio offering custom work across fine line, realism, Japanese, traditional and cover-ups.','1066 Somerset Street West, Unit 206','Ottawa','Ontario','K1Y 4T3','Canada','343-552-3449','Studio team','https://two0sixtattoo.com/','https://two0sixtattoo.com/','Fine line, realism, Japanese, traditional, cover-ups, piercing',0,'active','Verified from the official studio website on 2026-08-22'),
  ('relic-ottawa','Relic Piercing and Tattoo','Appointment-only Westboro studio offering neo-traditional and illustrative tattooing alongside professional piercing.','379 Danforth Avenue','Ottawa','Ontario','K2A 0E1','Canada','','Studio team','https://www.relicottawa.ca/','https://www.relicottawa.ca/','Neo-traditional, illustrative, colour, piercing',0,'active','Verified from the official studio website on 2026-08-22'),
  ('sage-tattoo-ottawa','Sage Tattoo and Art Gallery','Large Ottawa tattoo and piercing studio with specialists in realism, colour, black-and-grey and custom work.','2286 Carling Avenue','Ottawa','Ontario','','Canada','613-228-8896','Studio team','https://sagetattoo.com/','https://sagetattoo.com/','Realism, colour, black-and-grey, custom tattoos, piercing',0,'active','Verified from the official studio website on 2026-08-22'),
  ('barnstormer-studio-ottawa','Barnstormer Studio','Glebe studio producing custom, traditional, Japanese-inspired, black-and-grey and colour tattoos.','591 Bank Street','Ottawa','Ontario','K1S 3T4','Canada','613-233-8372','Studio team','https://barnstormerstudio.ca/','https://barnstormerstudio.ca/','Custom, traditional, Japanese-inspired, black-and-grey, colour',1,'active','Verified from the official studio website on 2026-08-22'),
  ('adrenaline-toronto-queen-west','Adrenaline Toronto — Queen West','Central Toronto tattoo and piercing studio welcoming appointments and walk-ins.','239 Queen Street West','Toronto','Ontario','M5V 1Z4','Canada','416-913-8805','Studio team','https://adrenalinetattoos.com/locations/','https://adrenalinetattoos.com/locations/','Custom tattoos, walk-in tattoos, piercing',1,'active','Verified from the official studio locations page on 2026-08-22'),
  ('adrenaline-vancouver-granville','Adrenaline Vancouver — Granville','Downtown Vancouver tattoo and piercing studio welcoming appointments and walk-ins.','1014 Granville Street','Vancouver','British Columbia','V6Z 1L5','Canada','604-669-6800','Studio team','https://adrenalinetattoos.com/locations/','https://adrenalinetattoos.com/locations/','Custom tattoos, walk-in tattoos, piercing',1,'active','Verified from the official studio locations page on 2026-08-22'),
  ('adrenaline-montreal','Adrenaline Montréal','Downtown Montréal tattoo and piercing studio welcoming appointments and walk-ins.','1541 Sherbrooke Street West','Montréal','Quebec','H3G 1L7','Canada','514-938-8884','Studio team','https://adrenalinetattoos.com/locations/','https://adrenalinetattoos.com/locations/','Custom tattoos, walk-in tattoos, piercing',1,'active','Verified from the official studio locations page on 2026-08-22'),
  ('prana-tattoo-montreal','Prana Tattoo and Piercing','Downtown Montréal studio offering traditional, fine line, realism, black-and-grey, colour and piercing.','17 Sainte-Catherine Street East','Montréal','Quebec','H2X 1K3','Canada','514-842-9559','Studio team','https://www.pranatattoo.ca/en','https://www.pranatattoo.ca/en','Traditional, fine line, realism, black-and-grey, colour, piercing',1,'active','Verified from the official studio website on 2026-08-22'),
  ('ambassador-tattoo-calgary','Ambassador Tattoo','Calgary custom tattoo studio specializing in traditional and neo-traditional work.','908 17 Avenue SW, Suite 312','Calgary','Alberta','','Canada','403-827-9995','Studio team','https://www.ambassadortattoo.com/','https://www.ambassadortattoo.com/','Custom, traditional, neo-traditional',0,'active','Verified from the official studio website on 2026-08-22'),
  ('calgary-tattoo-company','Calgary Tattoo Company','Calgary studio with a multi-artist roster and custom tattoo services seven days a week.','7144 Fisher Street SE','Calgary','Alberta','T2H 0W5','Canada','403-474-6660','Studio team','https://www.calgarytattoocompany.com/','https://www.calgarytattoocompany.com/','Custom tattoos, black-and-grey, colour, illustrative',0,'active','Verified from the official studio website on 2026-08-22'),
  ('got-ink-edmonton','Got Ink? Tattoo Studio','Edmonton studio producing custom black-and-grey and versatile one-on-one tattoo work.','14716 Stony Plain Road','Edmonton','Alberta','T5N 3S4','Canada','825-333-8282','Ryan','https://gotinkstudio.com/','https://gotinkstudio.com/','Black-and-grey, custom tattoos, realism',1,'active','Verified from the official studio website on 2026-08-22'),
  ('winnipeg-tattoo','Tattoos for the Individual','Established Winnipeg appointment studio offering custom work with occasional walk-in availability.','1767 Portage Avenue, Unit 1','Winnipeg','Manitoba','R3J 0E7','Canada','204-889-3943','Studio team','https://winnipegtattoo.com/','https://winnipegtattoo.com/','Custom tattoos, consultation, appointment work',1,'active','Verified from the official studio website on 2026-08-22'),
  ('rites-of-passage-saskatoon','Rites of Passage Tattoo','Saskatoon tattoo and piercing studio offering custom work, appointments and walk-ins.','634 10th Street East','Saskatoon','Saskatchewan','','Canada','306-956-8282','Studio team','https://www.roptattoo.com/','https://www.roptattoo.com/','Custom tattoos, walk-in tattoos, piercing',1,'active','Verified from the official studio website on 2026-08-22'),
  ('sin-on-skin-halifax','Sin on Skin Tattoo Studio','Downtown Halifax studio specializing in custom, colour, black-and-grey and cover-up tattoos.','5239 Blowers Street, 3rd Floor','Halifax','Nova Scotia','','Canada','902-446-6600','Studio team','https://www.sinonskin.ca/','https://www.sinonskin.ca/','Custom, colour, black-and-grey, cover-ups, realism',1,'active','Verified from the official studio website on 2026-08-22')
ON DUPLICATE KEY UPDATE
  name=VALUES(name),description=VALUES(description),address_line1=VALUES(address_line1),city=VALUES(city),
  province=VALUES(province),postal_code=VALUES(postal_code),country=VALUES(country),phone=VALUES(phone),
  owner_display_name=VALUES(owner_display_name),owner_instagram_url=VALUES(owner_instagram_url),
  instagram_url=VALUES(instagram_url),services=VALUES(services),walk_ins=VALUES(walk_ins),status='active',
  source_note=VALUES(source_note),updated_at=CURRENT_TIMESTAMP;
