-- French Quest cloud save snapshots — MySQL/MariaDB
CREATE TABLE IF NOT EXISTS french_quest_saves (
  user_id BIGINT UNSIGNED NOT NULL PRIMARY KEY,
  completed_challenge_ids LONGTEXT NOT NULL,
  xp INT UNSIGNED NOT NULL DEFAULT 0,
  hearts TINYINT UNSIGNED NOT NULL DEFAULT 5,
  streak INT UNSIGNED NOT NULL DEFAULT 0,
  theme VARCHAR(32) NOT NULL DEFAULT 'riviera',
  schema_version SMALLINT UNSIGNED NOT NULL DEFAULT 1,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_french_quest_updated (updated_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
